llvm/llvm-zorg

zorg/jenkins/monorepo_build.py
Since https://reviews.llvm.org/D69401 landed the bot has been setting unused
CMake variables for specifying test compilers which meant this bot hasn't
been testing anything since 2019. Reenabling the tests so that we can start
fixing the failing tests.
=> [lldb] Actually let the matrix bot test something

buildbot/osuosl/master/config/release_builders.py
We should be using BuildKite instead. That build bot is broken now anyways because it is using an unsupported compiler.
=> Remove obsolete libc++ release builder

buildbot/osuosl/master/config/builders.py
Test a LLVM build with the dynamic library enabled. Remove the
clang-x86_64-debian-new-pass-manager-fast builder since the new pass
manager has been the default since Feb 21.
I've modeled this after the existing `x86_64-fedora-clang` builder.
=> Replace new-pass-manager-fast builder with llvm-dylib-all

buildbot/osuosl/master/config/builders.py
The tests for the OCaml bindings fail when using the llvm.so dylib.
@gribozavr Does this look right to you?
=> Disable bindings on x86_64-debian-dylib builder

test/jenkins/test_monorepo_build.py, zorg/jenkins/monorepo_build.py
We don't want to include libc++ in LLVM_ENABLE_PROJECTS anymore, since
it's unsupported and the goal of this script is to test Clang, which
does not include libc++ headers anymore on Apple platforms.
=> [green dragon] Remove libc++ from monorepo builds

buildbot/osuosl/master/config/builders.py
A recent [change](https://github.com/llvm/llvm-project/commit/50d96f59d0966bdda6b3ac4f8964ed572435b847) to llvm-tablegen made it unusable under tsan. our bot would OOM all builds ever since. this flag should enable us to build tblgen in native setup, without tsan.
=> Use optimized tablegen in clangd builds

zorg/buildbot/builders/sanitizers/buildbot_cmake.sh
Like done for TSan, filter out the check_memcpy.c tests with the internal symbolizer.
=> [sanitizer] Filter out check_memcpy.c tests with internal symbolizer

buildbot/osuosl/master/config/builders.py
The immediate motivation is to fix the job (which currently fails because the environment doesn't support C++23 which the benchmarks require to compile), but building benchmarks should be unnecessary to publish the docs anyway.
=> [libc++] Don't build libc++ benchmarks in the `publish-runtimes-sphinx-docs` job

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/status.py, buildbot/osuosl/master/config/workers.py
As was suggested https://github.com/llvm/llvm-project/issues/56674#issuecomment-1690845357 that adds a configuration that should match build run by GitHub pull requests.
We are going to set up initially one worker per windows / linux architecture. It's unlikely that windows one will be able to catch up with every commit but we will monitor it and decide if e.g. adding one more worker might actually be fast enough to build every change.
=> Add builders for premerge-like configurations

zorg/buildbot/builders/StagedBuilder.py
* StagedBuilder.getCmakeBuildFactory
The factory provides a simple staged builder configuration to build the LLVM project unified tree.
This factory is a replacement for `UnifiedTreeBuilder.getCmakeWithNinjaMultistageBuildFactory` factory and it also can replace at least `FlangBuilder.getFlangOutOfTreeBuildFactory`.
=> Add a new build factory to create the staged builders (StagedBuilder).

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/status.py, buildbot/osuosl/master/config/workers.py
Add two new builders clang-x86_64-linux-abi-test and llvm-new-debug-iterators,
two new workers sie-linux-worker2 and sie-linux-worker3 as well as setup notifications for their failures.
I'm not sure what configuration we will use for the machines yet and wanted to get them into the staging server so that I can see what the timings are like and what state things are in at the moment before I commit to a configuration.
=> Add two new Sony builders and workers

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/status.py, buildbot/osuosl/master/config/workers.py
We are retiring the mlir windows bot. This removes it from zorg.
=> Remove mlir windows bot

buildbot/osuosl/master/config/builders.py
Add testing of BOLT instrumentation for AArch64 using trunk Clang binary built with stable Clang from Ubuntu.
=> [BOLT] Enable Clang-BOLT testing on aarch64

buildbot/osuosl/master/config/builders.py
Following https://discourse.llvm.org/t/llvm-ccache-build-is-deprecated/68431
=> Update ccache setting for mlgo buildbots

buildbot/osuosl/master/config/builders.py
Use trunk lld in BOLT tests instead of BOLT_LLD_EXE to reduce
maintenance burden. lld is cheap to build, and it helps to track lld
commits too.
=> [BOLT] Build lld to avoid test breakage

zorg/buildbot/builders/sanitizers/buildbot_android_functions.sh
A recent Clang driver will assume -stdlib=libc++ automatically for Android and will also automatically add $SYSROOT/usr/include/c++/v1 to the include search path.
This explicit -I path breaks libFuzzer when it builds and links its own copy of libc++ because there are two different libc++ copies on the include path.
=> [Android] Remove unneeded -stdlib and -I flags for C++

zorg/buildbot/builders/BOLTBuilder.py
Integrate nfc-stat-parser into NFC testing to report unexpected
time/memory regressions.
=> [BOLT] Check processing time and max RSS swings in nfc builder

zorg/buildbot/commands/LitTestCommand.py
https://github.com/llvm/llvm-zorg/issues/65
Listen to the `header` TTY stream and monitor the message like `command timed out: 1200 seconds without output running [b'ninja', b'check-clang-unit'], attempting to kill` sent from a worker.
=> Fixed the issue `Unclear buildbot failure email`

buildbot/osuosl/master/config/builders.py
ccache is now available on Windows on Arm machines and this
patch will enable to use to ccache instead of sccache on all
Windows on Arm buildbots hosted by Linaro.
=> Replace sccache with ccache for WoA bots

buildbot/osuosl/master/config/builders.py
- Enable `clean=True` to force build dir cleanup (avoiding processing
BOLTed clang).
- Use gcc/g++ for 1st stage clang binary to extend testing.
- Enable BOLT-PGO.cmake cache to test optimizing PGO+LTO clang.
- Track lld commits.
=> [BOLT] Align bolt-aarch64-ubuntu-clang with bolt-x86_64-ubuntu-clang

zorg/buildbot/builders/annotated/fuchsia-linux.py
This change fixes the fuchsia annotated builder to work in a Docker container.
=> Change fuchsia annotated builder to use getcwd() instead of "."

zorg/buildbot/builders/annotated/fuchsia-linux.py
Enable ccache when building LLVM in the annotated builder fuchsia-linux
=> Enable ccache for LLVM in fuchsia builder

buildbot/osuosl/master/config/status.py
Sivachandra has moved on from the libc project and ndesaulniers has joined. This patch ensures the notifications are going to the right place.
=> Remove sivachandra and add ndesaulniers in libc notification list

buildbot/osuosl/master/config/builders.py
We want to expand the dylib testing to include libclang-cpp.so and also to build projects like lld, lldb, and clang-tools-extra that consume the dylibs.
=> Build more projects with llvm-x86_64-debian-dylib

buildbot/fuchsia/Dockerfile, buildbot/fuchsia/buildbot.tac
This Dockerfile is used to build a Docker image that's used on all Fuchsia builders. Our infrastructure will automatically pick up any changes to this Dockerfile, rebuild and redeploy the image.
=> Dockerfile for Fuchsia builders

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/release_builders.py
* reduce a build path for the builders to avoid failures for the unix socket related tests (the expensive check builders).
* remove TMP/TEMP substitution for the release builders (we don't use a ramdisk for these builders).
We start getting the failures for the unix socket related tests when overriding TMP/TEMP env variables with the longer path on the Linux hosts, The tests create an unique path for the sockets based on TMP + uniqie name + socket name. The test gets failed when a total length of this path overflows a limit in 108 characters.
=> Update the builder configurations on as-builder-4(-rel) worker hosts.

buildbot/osuosl/master/config/builders.py
It appears that https://github.com/llvm/llvm-project/pull/70695 fixed an issue that prevented libc unit tests to be run in parallel.
=> [libc][AMDGPU] Enable parallel tests for libc on AMDGPU

buildbot/google/docker/buildbot-cpp20/Dockerfile
See https://github.com/llvm/llvm-project/pull/72348 for some context on why we need this upgrade.
=> Upgrade to Clang 17.0.6 in the C++20 buildbot

zorg/buildbot/commands/LitTestCommand.py
This is an update for https://github.com/llvm/llvm-zorg/pull/73
The command line with the test names is missing in clang unit tests. We must use the different regex to detect clang unit tests to properly update the path to the executable.
=> Fixed incorrect parsing of the failed Clang Unit test names

buildbot/osuosl/master/config/builders.py
We start getting the build timeout errors for the `flang-runtime-cuda-gcc` builder ([build](https://lab.llvm.org/buildbot/#/builders/267/builds/636)) after PR https://github.com/llvm/llvm-project/pull/76486. The reason is that some of added files take around or more than 1200 seconds (20 minutes, default timeout) to compile without any console output.
The most slowly built files:
* findloc.cpp, ~43min
* matmul.cpp, ~20min
* extrema.cpp, ~16min
* matmul-transpose.cpp, ~14min
All of those were compiled by `nvcc` for four GPU arch targets.
To fix the timeout error and reduce interferences with the other builders on the worker I have updated the builder configuration to compile only for the single GPU arch target. It reduces a compilation time for `findloc.cpp` file to 12 minutes. It reduces …
=> Update the 'flang-runtime-cuda-gcc' builder configuration.

zorg/buildbot/builders/annotated/fuchsia-linux.py
The annotated builder sets BUILDBOT_CLOBBER to empty string when clobber isn't requested so we need to handle that case correctly.
=> [Fuchsia] Handle BUILDBOT_CLOBBER correctly

zorg/buildbot/builders/annotated/fuchsia-linux.py
Use a unique build directory for each build to avoid incremental build correctness issues while making it possible to investigate past build issues.
=> [Fuchsia] Use a separate build directories

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
This bot adds clang and flang frontends to the OpenMP runtime on AMDGPUs. Given the current state of flang, this can still be seen quite experimental.
Also, this relies on a new worker that is not yet connected.
=> [OpenMP][Flang] Adds experimental OpenMP bot

buildbot/osuosl/master/config/builders.py
This enables an actual 8-way parallel testing of libc for GPU on AMDGPU. We limit the number of concurrent executions since we have some anecdotal evidence that highly-parallel execution can still provoke some issues. I think we should test some parallel execution though and we did not see hangs on other systems with low numbers of parallel jobs.
=> [LibC][AMDGPU] Enable 8-way parallel AMDGPU tests

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
This adds a sanity-check bot to the AMDGPU OpenMP Offloading bot infrastructure. It is a copy of the existing production bot, but with an updated OS and ROCm base-installation and running on a more potent machine.
=> [OpenMP] Adds another AMDGPU OpenMP bot

zorg/buildbot/builders/sanitizers/buildbot_functions.sh
llvm/llvm-project#77689 is not a fix.
This reverts commit 8202ffdd47b2197057cfa14c8f2153a20d3ddf37.
=> Reapply "Disabled libunwind, #96 was not enough"

buildbot/osuosl/master/config/builders.py
This should fix the build which started failing after https://github.com/llvm/llvm-project/commit/8f90e6937a,
see for example https://lab.llvm.org/buildbot/#/builders/57/builds/31930.
=> [clang-ppc64le-rhel] Also build libunwind

buildbot/osuosl/master/config/builders.py
The option doesn't make sense as clang is being built and BOLT tests can
use trunk clang instead.
=> Remove BOLT_CLANG_EXE from premerge builder

buildbot/osuosl/master/config/builders.py
Enable 'ccache' cached builds.
=> Update 'llvm-clang-x86_64-win-fast' builder.

buildbot/osuosl/master/config/builders.py
As more than 400 tests are currently failing for the Sparc target, it makes little sense to test two-stage builds until these issues have all been sorted out. Thus, switch sparc64 builds on Linux to single stage.
=> Switch sparc64-linux to single-stage builds

zorg/jenkins/jobs/jobs/llvm-coverage
Fix the build after llvm-project 8f90e6937a (e.g.
https://green.lab.llvm.org/green/job/coverage/535/).
=> Add libunwind to runtime build for llvm-coverage

buildbot/osuosl/master/config/builders.py
As LoongArch has already been in the LLVM_ALL_TARGETS instead of LLVM_ALL_EXPERIMENTAL_TARGETS list in the llvm-project, this patch will match cmake config to it on LoongArch builder.
=> [Clang] Move LoongArch from LLVM_EXPERIMENTAL_TARGETS_TO_BUILD to LLVM_TARGETS_TO_BUILD

buildbot/osuosl/master/config/builders.py
Removing the libcxx,libcxxabi, and libunwind runtimes from being built and tested on the clang-ppc64le-rhel buildbot.
=> [LibC++] Remove libcxx,libcxxabi,libunwind from clang-ppc64le-rhel

zorg/buildbot/changes/llvmgitpoller.py
`project=None` will cause the following exception
```
File "/zorg/buildbot/changes/llvmgitpoller.py", line 188, in _process_changes
project=",".join(projects) if projects else "llvm-project",
builtins.TypeError: sequence item 0: expected str instance, NoneType found
```
Use a dummy str instead.
=> [LLVMPoller] Fix an exception in case of changing files in the root

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
Adding two new mac builders since I will soon have some spare machines lying around idle and we don't seem to have much mac coverage on the main buildbot.
Also reduced the number of parallel threads used by a few other workers that were sharing another machine's distributed compilation resources (that machine will be redeployed as one of the new mac workers).
=> Add 2 new mac workers/builders as well as reallocate resources on some existing workers.

zorg/buildbot/builders/annotated/fuchsia-linux-staging.py
This patch updates the configuration for the Fuchsia staging builder to
use a single stage build to reduce the build time.
=> Use a single stage build for Fuchsia toolchain

zorg/buildbot/builders/annotated/fuchsia-linux-staging.py
We don't need the runtime variants on build bots. This patch disable it
so the build time can be further reduced.
=> Stop building Fuchsia runtime variants on Fuchsia staging bots

buildbot/osuosl/master/config/builders.py, zorg/buildbot/builders/LLDBBuilder.py
Previously the builder class argument "jobs" defaulted to a string to use with `WithProperties`. This assumed that every worker has a "jobs" property, which is no longer true after changes to Linaro's workers.
The behaviour of `WithProperties` is detailed here: https://github.com/buildbot/buildbot/blob/6e7218792bc324584af980bd1abb4d8b6a5055b8/master/docs/manual/configuration/properties.rst#withproperties
As no builder was using the `jobs=` argument I have removed it and adapted code from `NinjaCommand` to add `-j<jobs>` only if the property exists.
Meaning that Linaro's workers that do not have a "jobs" property will not be limited. `lldb-x86_64-debian` will have a `-j` because its worker specifies `'jobs': 72`.
According to Buildbot docs, `WithProperties` should be replaced with …
=> [LLDB] Remove builder class jobs option, only use worker's jobs property if present

buildbot/osuosl/master/config/builders.py
This disables host/device and device/host transfers via the SDMA engines for the OpenMP Offload AMDGPU buildbots.
The motivation is a known issue of a potentially missed synchronization tracked via https://github.com/ROCm/ROCm/issues/2616.
This change was rolled-out to one of the staging bots previously via https://github.com/llvm/llvm-zorg/pull/114 and seemed to remove the flakiness we were observing.
=> [OpenMP] Disabling SDMA transfers AMDGPU offload bots

zorg/buildbot/builders/ClangBuilder.py
After https://reviews.llvm.org/D140236 (and other changes I'm sure), flang doesn't need pgmath to link executables.
Seems good to be testing based on that, plus it will clean up a bunch of warnings from Linaro's bots:
flang-new: warning: -lpgmath: 'linker' input unused [-Wunused-command-line-argument]
That end up polluting the emails we send on a failed build.
=> [flang] Remove pgmath linker flag for test suite

zorg/buildbot/builders/annotated/fuchsia-linux.py
This patch copies Fuchsia's staging build bots configurations to the
Fuchsia prod builders, which disables stage-2 builds and enable Fuchsia
runtimes build.
=> Copy Fuchsia staging builder config to prod builders

zorg/buildbot/changes/llvmgitpoller.py
LLVMPoller can be configured to use other `repourl` for test/debug purpose. But LLVMPoller always provides `https://github.com/llvm/llvm-project` as the repository while creating a new change. Then `GitHubStatusPush._extract_github_info()` extracts invalid `repo_owner` and `repo_name`. This patch fixes the issue described above.
=> [LLVMPoller] Fix invalid repository while creating a new change

zorg/buildbot/builders/LLDBBuilder.py
Which is what I tried to do in 330340b14f6325d76c96cb1713d29c4258e541b8, but forgot one detail. If there is no property the options have empty string added to them.
This means you get this:
`ninja "" ""`
And ninja thinks that those are targets to build, which don't exist of course.
NinjaCommand already handles this by removing any empty arguments as the final step of building the options. So use that for our ninja steps instead.
=> [lldb] Use NinjaCommand instead of manually building options

buildbot/osuosl/master/config/builders.py
How to build libc for GPU is about to change significantly, which requires an update to the way it is built in the bot.
After some back and forth, it appears that it cannot be easily added to the `-DLLVM_ENABLE_RUNTIMES` and instead requires some special handling. Thus, for the libc bot we intentionally work around the `enable_runtimes=auto` option and instead enable `'openmp'` and `'compiler-rt'` manually in the bot specification.
In addition, we specify the new CMake flags for the libc build on AMDGPU.
=> [libc] Update libc build config

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/status.py
This change makes 3 updates to the SIE bot configuration.
1. Retire the llvm-new-debug-iterators worker as it is no longer needed, and remove the notification for this worker.
2. Reassign sie-linux-worker3 to perform the llvm-clang-x86_64-gcc-ubuntu build.
3. Add notifications for myself for my added darwin builders that I previously forget to add when I added the bots.
=> Remove llvm-new-debug-iterators worker, reassign sie-linux-worker3 and add notifications for darwin builders.

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/release_builders.py, buildbot/osuosl/master/config/status.py, buildbot/osuosl/master/config/workers.py
Add a new release builder for the AArch64 Darwin target, and a new worker to share build responsibilities for the llvm-clang-aarch64-darwin builder.
=> Add a new Darwin worker and release builder

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/release_builders.py, buildbot/osuosl/master/config/workers.py
I am shuffling around the builder assignments for a few workers, so needed to remove the hard coded values as they were causing the machines to become unresponsive when I scaled down the hardware. Also update the llvm-clang-x86_64-gcc-ubuntu release builder to use the sie-linux-worker3 worker (I forgot to update this in a previous change when I updated the non-release job to use this worker).
1. Remove jobs property for 2 linux workers
2. Switch llvm-clang-x86_64-gcc-ubuntu-release to sie-linux-worker3
3. Remove -j value for some LLVM_LIT_ARGS for 2 builds
4. Remove argument LLVM_PARALLEL_LINK_JOBS for 2 builders
=> Make a few buildbot changes to the SIE buildbots

buildbot/osuosl/master/config/builders.py, zorg/buildbot/builders/OpenMPBuilder.py
Enable passing additional lit arguments per bot to the `ninja check-openmp` configuration.
This can be used to set, e.g., timeouts or enable timing the individual tests. The latter requires the Python package `psutil` to be installed.
=> [OpenMP] Possiblity to add lit args to check-openmp

buildbot/osuosl/master/config/builders.py
Updating PowerPC bots to use the upstream CMake support for ccache:
```
-DCMAKE_C_COMPILER_LAUNCHER=ccache 
-DCMAKE_CXX_COMPILER_LAUNCHER=ccache
```
=> PowerPC Linux: Replace usage of LLVM_CCACHE_BUILD with CMAKE_C_COMPILER_LAUNCHER=ccache

buildbot/osuosl/master/config/builders.py
Updating to Apple Clang 1500.3.9.4 fixes the problem that was causing test failures.
Build/test is now passing: https://lab.llvm.org/staging/#/builders/188/builds/444.
=> Revert "Add -DLLVM_DISABLE_ASSEMBLY_FILES=ON to work around a bug in Apple Clang (#129)"

buildbot/osuosl/master/config/builders.py, zorg/buildbot/builders/UnifiedTreeBuilder.py
Trying to fix the pre-merge bots which are broken right now.
I can't test it though since I don't have SSH access to these bots.
=> Try adding an option to automatically install MLIR pip requirements to getCmakeWithNinjaBuildFactory

buildbot/osuosl/master/config/builders.py
I was looking at the cmake command for the llvm-clang-x86_64-darwin builder and noticed that two of the arguments were being combined and traced that back to a missing comma in the arguments for the specification of this builder. This change puts that comma back.
=> Fix a comma that was accidentally deleted in an argument list.

zorg/buildbot/builders/annotated/hip-build.sh
Previsouly the bot build runtime first using the old llvm/clang.
This does not work of libc++ or other runtime requires new llvm/clang.
=> Fix hip-build.sh to build llvm/runtime together

zorg/jenkins/build.py
Stage 2 jobs are currently broken. E.g.:
https://green.lab.llvm.org/job/llvm.org/job/clang-stage2-Rthinlto/59/
```
CMake Error at cmake/modules/HandleLLVMOptions.cmake:714 (message):
LLVM_ENABLE_MODULES is not supported by this compiler
Call Stack (most recent call first):
CMakeLists.txt:953 (include)
```
While the root cause of the stage 1 compiler not supporting modules is investigated we should disable building with modules to get signal from the job.
It appears that `LLVM_ENABLE_MODULES` is on by default because of the `clang/cmake/caches/Apple-stage2*.cmake` initial cache files (see 1cc3474ec11dcb267544e5b4630d52b3aa3e66b3 in llvm-project repo)
rdar://125123985
=> [GreenDragon] Workaround Stage 2 bots being broken

buildbot/osuosl/master/config/builders.py
A new bitcode format for debug info was added in LLVM in
[e419084da7a00b269368aeb95698e0d36b24e8ec](https://github.com/llvm/llvm-project/commit/e419084da7a00b269368aeb95698e0d36b24e8ec) (currently reverted).
Several tests started failing for this stage2 builder: https://lab.llvm.org/buildbot/#/builders/179/builds/9629
The error indicates the tests are using an incompatible lld to load the new bitcode:
ld.lld: error: Invalid value (Producer: 'LLVM19.0.0git' Reader: 'LLVM 17.0.6')
Locally, re-enabling the currently reverted patch, these tests pass if LLD is built with LLVM_ENABLE_PROJECTS, and fail otherwise.
---
I don't really know how zorg works - I'm not sure if this is the right way to get the stage2 build to build an lld for those tests to use. I think a stage1 build of lld would also …
=> clang-aarch64-full-2stage: build lld for stage2 tests

buildbot/osuosl/master/config/builders.py
* collapse the build requests to reduce the build queue.
* added CUDA compiler flags to the CMake configuration step.
=> Update configuration for flang-runtime-cuda-clang/gcc builders.

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
The bot runs a build of clang, flang, llvm, mlir, lld and openmp inside a SLES container.
It does not currently run check-openmp as we do not have a GPU available for the offloading runtime tests.
=> [OpenMP] Adds SLES 15 SP4 build bot

tasks/tasktool/bin/build, tasks/tasktool/bin/task, tasks/tasktool/tasktool/build.py, tasks/tasktool/tasktool/task.py
* Update tasktool files to python3 and allow task tool to be able to run independently from source repo without having to rely on external systems (CI) to set PYTHONPATH
=> [green-dragon-migration] update the tasktool files to python3

buildbot/osuosl/master/config/builders.py, zorg/buildbot/builders/FlangBuilder.py
As discussed in Discourse and proposed in
https://github.com/llvm/llvm-project/pull/80874, Flang will start
to use C/C++ header files and Fortran modules from OpenMP runtime.
When the mentioned PR lands, all of Flang's OpenMP tests will be
skipped as unsupported, unless the OpenMP project is enabled.
=> [flang] Enable OpenMP project for Linaro's bots

zorg/jenkins/jobs/requirements.txt
* Add the requirements.txt file for jenkins CI agents. We separate this from the global requirements.txt file since it's specific to green dragon CI agents, and we don't want to inadvertently break any build bots
=> [green-dragon-migration] check in jenkins requirements file

buildbot/osuosl/master/config/builders.py
Building LLVM with libc++ and OpenMP as a runtime on a glibc based
system causes some hard to fix build failures (see
https://github.com/llvm/llvm-project/issues/61693).
As the point of building against libc++ was to make sure flang works
well with it, adding OpenMP doesn’t help that, and flang OpenMP
tests are already enabled on other flang bots, just disable OpenMP
on flang-aarch64-libcxx.
=> [flang] Disable OpenMP on flang-aarch64-libcxx bot

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
Pass a path to LIBCUDACXX source code to avoid the following build warnings:
warning #20014-D: calling a __host__ function ...
=> Enable FLANG_LIBCUDACXX_PATH for 'flang-runtime-cuda-gcc' builder.

tasks/lnt-ctmark.sh, tasks/lnt-testsuite.dep, tasks/test-suite-verify-machineinstrs.sh, tasks/utils/venv.sh
* Update task shell scripts to use python 3
* Update any shell scripts pulling the compiler to install the awscli dependency needed
* Don't require virtualenv as with python3 we just use venv built into the python stdlib
=> [green-dragon-migration] Update task shell scripts

zorg/buildbot/builders/FlangBuilder.py
After https://github.com/llvm/llvm-project/pull/87822
we can specify real relative paths from the flang build directory
to the directories containing LLVM/CLANG/etc. projects' config
files.
=> Fixed relative paths for Flang out-of-tree builder.

buildbot/osuosl/master/config/builders.py
With this patch lunch target will be aosp_arm64-trunk-userdebug
Doc:  https://source.android.com/docs/setup/build/building#view_the_current_target
Should fix buildbot failure: https://lab.llvm.org/buildbot/#/builders/82/builds/15143
=> Use updated lunch configuration format

buildbot/osuosl/master/config/builders.py
This is in anticipation of landing the move to offload. We have one buildbot that already runs the configuration with offload enabled, which will hopefully turn green once the patch lands.
Once things are fine on that end, we can land this patch to enable the offload runtime in the other buildbots as well.
=> [OpenMP] Add offload to other buildbots

buildbot/osuosl/master/config/builders.py
This is making the AMDGPU offload buildbots depend on the 'offload' project. FWICT this should work with the current buildbot implementation we have, but someone more knowledable should confirm that this works.
=> [Offload] Make buildbots depend on offload project

buildbot/osuosl/master/config/builders.py
This adds compiler-rt as runtime to build to unify our buildbots and removes the unneeded manual addition of openmp as a runtime to build in the CMake options list.
=> [OpenMP][AMDGPU] Build compiler-rt as runtime

buildbot/osuosl/master/config/builders.py
This adds `check-offload` to the AMDGPU OpenMP Offloading production buildbot, to re-enable coverage of OpenMP offload testing.
=> [Offload] Enable check-offload in AMDGPU prod bot

zorg/jenkins/jobs/jobs/llvm-coverage
* Update llvm coverage job
the job has been updated to:
* Run on the correct labels
* download artifacts to S3
* Set environment variables in `environment` closure when possible
* Setup python3 venv with all dependencies to build/test
* Save coverage report as an artifact on the job rather than scp to labmaster 2
=> [green-dragon-migration] add llvm coverage job

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
This adds a dockerized RHEL 9.4 buildbot that builds clang, flang, mlir, openmp, offload, llvm and lld and runs all the tests.
=> [Offload] Adds RHEL 9.4 buildbot

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
This addresses several problems with Offload/OpenMP AMDGPU buildbots:
- Change worker name for RHEL 9.4 to not contain a '.'
- List 'compiler-rt' in 'depends_on_projects' lists to not generate false blame emails as pointed out by Galina in a separate review.
- Update the SLES builder environment to add /opt/rocm/lib path to the LD_LIBRARY_PATH environment variable.
=> [Offload][OpenMP] Various fixes to AMDGPU offload bots

buildbot/osuosl/master/config/builders.py
Currently the default toolchain is used:
- gcc (GCC) 13.0.0 20221013 (experimental)
- GNU ld (GNU Binutils) 2.39.50.20221029
But recently we find that a new added llvm unittest (llvm/unittests/Frontend/OpenMPDecompositionTest.cpp) can't be compiled by the default toolchain (causing memory exhausted and killed by the system). Error:
```
command timed out: 1200 seconds without output running [b'ninja', b'check-all'], attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=1669.062469
```
See https://lab.llvm.org/staging/#/builders/5/builds/4199.
This patch fixex this issue by switching to clang+lld (v17.0.6).
An alternative (workaround) is setting `useTwoStage=True` and `testStage1=False`, but I think we'd better to create a dedicated builder for that in …
=> [LoongArch] Switch the toolchain used by the `clang-loongarch64-linux` builder from default to clang+lld

zorg/jenkins/jobs/jobs/lldb-cmake-matrix
will fix
```
ModuleNotFoundError: No module named 'requests'
```
=> Activate venv in 17.0.6 build

zorg/buildbot/builders/annotated/clang-windows.py
PDB generation is resource-intensive and does not perform well for statically linked unit tests. The stage2 build generates PDBs to exercise clang-cl's debug info generation abilities, but we generally do not use the debug info from the stage 1 builds. PDB build errors are also a common source of builder unreliability and lead to excessive disk usage, so disable them for now.
Here is a recent example of PDB unreliability:
https://lab.llvm.org/buildbot/#/builders/123/builds/26898
```
... GeneratorTest.cpp: fatal error C1051: program database file, '...\vc140.pdb', has an obsolete format, delete it and recompile
```
=> Disable PDB generation in stage1 of the clang-cl self-host bot

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
For background, I don't expect these builders to graduate from the staging buildmaster in the current configuration. I'm spinning them up so we get some slow feedback while I, in parallel, explore alternative build configs that make better tradeoffs in terms of response time vs feedback.
These are all qemu-system based. Please note that the first commit adds a new ability to set cmake flags that apply only to the second-stage build, which I use to apply `-march` that the system compiler may not understand as well as to have ccache enabled for the first stage only. Happy to split that out to a separate PR if you prefer.
=> [RISCV] Add new "native" (qemu-system) builders

zorg/buildbot/builders/ClangBuilder.py
The way that change was indented meant that the cmake/build/check steps of stage 2 were only added if extra_stage2_cmake_args was not empty.
This caused any 2 stage builder without those extra options to skip building stage 2. Which left them green but not doing their
job, or red if they tried to run the test suite using stage 2.
=> Fix ClangBuilder after f59269f1ef7823fe68775d9a2fcc975673654bae

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/release_builders.py, buildbot/osuosl/master/config/workers.py
* llvm-clang-win-x-{armv7l,aarch64}-release
* llvm-clang-win-x-{armv7l,aarch64}
Removed DEFAULT_SYSROOT from the build configurations. Use the local clang configuration files instead.
More details could be found here:
https://github.com/llvm/llvm-project/issues/94284
=> Update configuration for armv7l/aarch64 Win-to-Linux cross toolchain builders.

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/release_builders.py, buildbot/osuosl/master/config/workers.py
Missed configuration for the workers hosting the release builders.
See #199 for details.
Related https://github.com/llvm/llvm-project/issues/94284
=> Update configuration for armv7l/aarch64 Win-to-Linux cross toolchain release builders.

buildbot/osuosl/master/config/builders.py
The containerized RHEL bots use custom CPU sets from the docker runtime and as a result this test fails reliably.
XFAIL the test on those two platforms.
=> [Offload][OpenMP] XFail proc-bind test on containered bots

zorg/buildbot/builders/ClangBuilder.py
After the LLVM buildbot maintenance, 2-stage builders started to
fail with the following error:
Unknown value for CMAKE_BUILD_TYPE: {stage2_config}
=> Fix 2-stage builders

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
Some changes to the clang-sparc64-linux configuration in the hope to fix the linking timeouts.
=> sparc64 linker and jobs changes

zorg/buildbot/reporters/utils.py
Here is the sample https://lab.llvm.org/buildbot/#/builders/101/builds/263
The failed step 3 has 2 logs `preamble` and `stdio` with the same type `s`. We must select the second log in this case.
=> Use lower priority for 'preamble' logs. Use higher priority for the rest stdio.

buildbot/osuosl/master/config/builders.py
In contrast to `check-openmp`, `check-offload` is not implicit. Also add `--time-tests` to be able to see the duration of each test.
Thanks to @jplehr for the hint.
=> [OpenMP][Offload] Enable check-offload for CUDA OpenMP builders

zorg/buildbot/builders/annotated/libc-linux.py
The build bot fails with the current message:
clang-15: error: argument unused during compilation: '-fuse-ld=lld'
because we are passing the fuse-ld flag as a compilation argument.
This patch sets it to CMAKE_EXE_LINKER_FLAGS_INIT so it can be loaded by LD_FLAGS instead.
=> [RISCV] Move fuse-ld flag to CMAKE_EXE_LINKER_FLAGS_INIT

zorg/buildbot/builders/annotated/hip-build.sh
Build compiler-rt as runtime instead of project. This will use freshly built clang to build compiler-rt instead of the system compiler. Also use lld to link compiler-rt. Both can lower the risk of encounter issues with old system compiler and linker.
Fixes buildbot failure https://lab.llvm.org/buildbot/#/builders/123/builds/1580
=> fix hip-build.sh about compiler-rt

zorg/buildbot/process/factory.py
We can get `IRenderable` (util.Interpolate) into `factory.pathRelativeTo()` from the builder configuration. We cannot process IRenderables here because of lack of required data. Just gently pass through that kind of arguments.
=> [zorg] Gently pass through the IRenderables in factory.pathRelativeTo static method.

zorg/buildbot/process/factory.py
This parameter is used to apply suffixes to the step names when factory is used as a nested factory for another one. The suffix will be added to the step name separated by dash symbol.
As example for 'stageX' hint the following step names will be generated for the factory's steps:
cmake-cofigure => cmake-configure-stageX
build => build-<target>-stageX
=> Add a new 'hint' argument for LLVMBuildFactory factory class.

zorg/buildbot/builders/UnifiedTreeBuilder.py
This argument can be used to apply suffixes to the step names when factory is used as a nested factory for another one.
The suffix will be added to the step name separated by dash symbol.
=> Add new 'hint' argument for UnifiedTreeBuilder.getCmakeExBuildFactory() factory.

zorg/buildbot/builders/UnifiedTreeBuilder.py
The IRenderable objects could be passed through the factory arguments. Do not wrap them in IRenderable (Interpolate) directly inside of the factory. Leave them 'as is' or use "%(kw:val)s" (or util.Transform) if it is necessary to do something with that kind of arguments.
=> Fix usage of IRenderable arguments within UnifiedTreeBuilder.getCmakeExBuildFactory factory.

zorg/buildbot/builders/annotated/libc-linux.py
Currently the buildbot is failing to find lld, so I added a few flags I use locally to force cmake to use lld.
=> [RISCV] Try to fix linker error for rv32

test/buildbot/builders/unified_cmakeex.py, zorg/buildbot/builders/UnifiedTreeBuilder.py
The changes for UnifiedTreeBuilder.getCmakeExBuildFactory factory and its test:
* updated the step formatting with 'hint' argument (avoid usage of substitutions).
* allowed only 'str' or None for the 'hint' argument.
* updated 'test/buildbot/builders/unified_cmakeex.py' test for the factory changes accordingly.
See #235 for more details.
=> Fix failed test/buildbot/builders/unified_cmakeex.py test (issue #235).

test/buildbot/builders/Import.py
This test had Python2 style prints, and needs to call ClangBuilder.getClangCMakeBuildFactory rather than ClangBuilder.getClangBuildFactory.
=> [test] Fix errors in Import.py test

buildbot/osuosl/master/config/builders.py
The libc buildbots use the builder's name to enable/disable libc features, so we add 'fullbuild' to the bot's name to enable libc's fullbuild.
=> [libc] Rename riscv32 buildbot to enable fullbuild

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/release_builders.py, buildbot/osuosl/master/config/workers.py
* moved to UnifiedTreeBuilder.getCmakeExBuildFactory
* moved Aarch64 release builder to as-builder-2 worker (same as post-commit builder)
=> Update Aarch64 Windows cross toolchain builders.

buildbot/osuosl/master/config/builders.py
Removed `--min/max-gdbserver-port` arguments when executing the lldb-server instance on the remote target host. Looks like these arguments are not working properly, lets just avoid using them for awhile.
Removed '--log-channel' and '--log-file' arguments for the lldb-server instance as useless for this run configuration.
Removed the remote target rebooting after the tests get done.
=> Update 'lldb-remote-linux-ubuntu' builder, remove --min/max-gdbserver-port arguments.

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py, zorg/buildbot/builders/sanitizers/buildbot_selector.py
RHEL 7.9, the only remaining officially supported Big Endian
Linux operating system, has reached its end of life. This patch
removes these buildbots due to their host and target arch
lack of OS security fixes and support.
=> Removing the ppc64be buildbots due to ppc64 linux OS EOL

buildbot/osuosl/master/config/builders.py
Now that CUDA bots run libc-on-GPU tests, we want to trigger the tests on libc and offload changes, too.
=> [CUDA] Add libc and offload to the depends_on_projects

zorg/buildbot/builders/ClangBuilder.py
When https://github.com/llvm/llvm-lnt/commit/768874171529d31d12adb032df57b1c5f1c1fa77 enabled using Ninja, it removed the -k flag from make. -k causes make to carry on if there's a build failure.
Without this flag, a single compilation failure turns into thousands of missing executables in the final results. As subsequent targets are not built.
https://github.com/llvm/llvm-lnt/pull/25 is adding an option to the lnt runner to pass options to the build tool.
This PR uses that to pass -k to make to restore the old behaviour on the build bots.
=> [ClangBuilder] Pass -k to make for test-suite runs

buildbot/osuosl/master/config/builders.py
This is step 1 to addressing the rapidly expanding build queues we're seeing (#250).
The bot is currently on silent, and the plan is:
* Mark all builds as clean (we use ccache so it shouldn't be a big impact).
* Clear the existing requests.
* See what happens to the queue.
It's possible we will need a follow up to make collapsing work, but this is the first step either way.
=> Make all clang-aarch64-full-2stage builds clean builds

buildbot/osuosl/master/config/builders.py
Since https://lab.llvm.org/buildbot/#/builders/18/builds/3578 the build has been failing with:
```
FAILED: lib/libclang-cpp.so.20.0git
: && /usr/local/bin/c++ -fPIC -fPIC -fno-semantic-interposition <...> -lm  /usr/lib/arm-linux-gnueabihf/libz.so && :
/usr/bin/ld.gold: internal error in open, at ../../gold/descriptors.cc:99
```
gold is no longer maintained and in my own experience hitting this same sort of error, my only solution was to switch to ld or lld.
There's no particular reason to use gold here I think it was just set that way before lld was useable on Arm.
Since we're linking clang with it we might as well use it in tests too, so make lld clang's default linker.
=> [lldb][Arm] Use lld for linking and tests

buildbot/osuosl/master/config/builders.py
For #102513
It should not be needed after https://github.com/llvm/llvm-project/pull/110986.
This reverts commit 73d07e033335e77f64a4ca0e202a34609e926662.
This reverts commit d0f47695ab36b38a4d1192d9ac4fe818b1f0b79c.
=> Revert "[windows] Increase timeout for sanitizer-windows"

buildbot/osuosl/master/config/builders.py
dotest.py flags are replaced with CMake flags introduced in https://github.com/llvm/llvm-project/pull/95986 to run Shell tests remotely.
Also, USE_LLVM_TOOLS is removed since it's implied by default that LLVM tools will be used for API tests since https://github.com/llvm/llvm-project/pull/109961.
=> [lldb] Flags for running Shell tests remotely on "lldb-remote-linux-ubuntu" builder

buildbot/osuosl/master/config/builders.py
This makes using libunwind the default and work around a breakage in check-flang when setting libgcc as the default unwind lib.
(Should I remove the unrelated whitespace changes?)
=> [CI] Using libgcc breaks Driver test

zorg/buildbot/builders/ClangBuilder.py
See https://discourse.llvm.org/t/proposal-rename-flang-new-to-flang/69462 for background.
This is to be landed once https://github.com/llvm/llvm-project/pull/110023 has landed.
=> ClangBuilder: Use "flang" instead of "flang-new" for the test suite

buildbot/osuosl/master/config/builders.py
Build the latest Aarch64 cross toolchain including all required libraries & etc to build the lldb-server and the tests.
=> Build latest cross Clang during 1st stage of the LLDB remote-linux builder.

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
This updates LLVM WoA bots with following changes:
1) Do not run stage1 testing on 2 stage clang bot. 
2) Remove redundant workers.
3) Remove -DCOMPILER_RT_BUILD_PROFILE=OFF
4) Add compiler-rt to single stage bot
5) Set clean=False for the 2stage bots
6) Set "-DCLANG_DEFAULT_LINKER=lld" for all WoA bots
=> Update LLVM WoA buildbots for better coverage

zorg/jenkins/jobs/jobs/lldb-statistics, zorg/jenkins/jobs/util/run_lldb_metrics.sh
This patch adds a new job to collect LLDB metrics.
This is heavily based on the `debuginfo-statistics` job (but currently doesn't publish data to LNT).
Currently this job would do the following:
1. Check out the Clang 19.x release and build it
2. Use the LLDB and Clang from the `lldb-cmake-intel` job (not actually sure if that job publishes the right artifacts at the moment) to run the `run_lldb_metrics.sh` script.
3. Said script will attach LLDB to Clang/LLDB and run various commands. Then it will dump the `statistics dump` command to `stdout` (note we don't do any kind of averaging of these over multiple runs, since the metrics we care about **should** stable across runs). We also currently run these test-scenarios through `hyperfine` and dump the timing data. But maybe for a first …
=> [zorg][lldb] Add new LLDB metrics bot

buildbot/osuosl/master/config/builders.py
Pass a worker specific property value as a toolchain's sysroot path for the toolchain build stage 1 of the builder.
=> Fix toolchain's sysroot for lldb-remote-linux-ubuntu builder.

zorg/jenkins/jobs/jobs/lldb-cmake-intel
We need to install so we can actually create the binary dir which is then converted to the tarball
=> Run cmake install to build package

.github/workflows/lit-tests.yml
This adds a GitHub action to at least run the very minimal lit tests we have for zorg itself. With appropriate repository settings (perhaps it just works as-is? I've tested a variant on a downstream fork), it should provide pass/fail for both PRs and commits.
The GH Actions in the main llvm-repos tend to be gated on `if: github.repository_owner == 'llvm'`, which I've copied across here.
There's a question mark about how to handle `test/jenkins/test_build.py`. I've marked it XFAIL as a command-line `lit` option, as the test ends up trying to call `xcrun` which has no hope of succeeding on Linux. But perhaps the test is fixable, or it would be better to mark the test itself XFAIL. Either way, I think the GH Action in the PR is definitely an improvement over the status quo.
=> [GHA] Add GitHub Action to run the tests for llvm-zorg itself

zorg/jenkins/jobs/jobs/clang-3.4-debuginfo-statistics
The run order should be the GIT_DISTANCE of the stage 1 compiler which is being used to build the historic compiler.
=> [clang-3.4-debuginfo-statistics] Fix the LNT submissions run order

buildbot/osuosl/master/config/builders.py
For #250.
This bots can't catch-up with `clean_obj` requests, but they do clean build anyway.
Maybe we should do the same for all sanitizer builders, but seems they are OK as is.
=> [sanitizer] Mark bootstrap builder as 'clean'

zorg/buildbot/builders/sanitizers/buildbot_functions.sh
Reverts llvm/llvm-zorg#295
Try again according to https://github.com/llvm/llvm-zorg/pull/266#issuecomment-2460946503
=> Revert "Reapply "[sanitize] Don't build older then 1h requests""

zorg/buildbot/builders/sanitizers/buildbot_functions.sh
The build tree layout does not necessarily match a valid libc++
installation tree, so install libc++/libc++abi first.
This is needed for https://github.com/llvm/llvm-project/pull/115379
=> Link against installed libc++/libc++abi when bootstrapping

buildbot/osuosl/master/config/builders.py
Fixes syntax errors in cmake code when passing Windows-style path as a string variable during the cmake configuration, such as `CMAKE_C_COMPILER=c:\buildbot\as-builder-10\lldb-x-aarch64/build/bin/clang.exe`, when running `lldb-remote-linux-win` builder.
Error:
Invalid character escape '\b'.
To fix, use ':PATH' var type suffix for the passing variables that contain the path values.
=> Fixes CMake configuration failures related with Windows-style/mixed path.

buildbot/osuosl/master/config/workers.py, buildbot/osuosl/master/master.cfg
This makes it (relatively) easy to test a builder setup locally. The buildmaster and the web interface should be bound only to local interfaces for security reasons (you can use ssh port forwarding if wanting to run on a server).
---
This patch ended up fairly small, but it needed quite a lot of fiddling about to get something that works and requires such minimal changes. I assume everyone has their own flows or downstream patches for testing with a local buildmaster, but I want to make it substantially easier for anyone to do this without repeating that effort. With this change, you just need to set the BUILDMASTER_TEST environment variable when starting the buildmaster, and it will bind to local interfaces and default to a "test" password for workers. The web interface is configured …
=> Add local testing mode to the buildmaster config

buildbot/osuosl/master/config/builders.py
Since flang depends on MLIR, depend on MLIR for changes to catch problems early.
=> [AMDGPU][Flang] Adds MLIR as dependency

zorg/jenkins/jobs/jobs/lldb-cmake-matrix
Don't poll or include changelist for the static tags which are checked out (llvmorg-17.0.6, llvmorg-15.0.1). This should hopefully reduce the changeless to just those on the main branch
=> don't poll or include changelog for release branches

buildbot/osuosl/master/master.cfg
BUILDBOT_TEST is sufficiently descriptive (after all, 'buildbot' is the package name and the name of the binary invoked to create a buildmaster) and it's possible upstream may later remove the buildmaster terminology <https://github.com/buildbot/buildbot/issues/5382> or alternatively we might move away from it downstream. As such, it seems prudent to use a name that would be unaffected.
----
This came partially from discussion at https://github.com/llvm/llvm-project/pull/115024 - I figure tweaking the name is a lot easier now, before it's fully documented/advertised and part of people's workflows, than later.
=> Rename BUILDMASTER_TEST to BUILDBOT_TEST

zorg/buildbot/builders/ClangBuilder.py, zorg/buildbot/process/buildrequest.py, zorg/buildbot/process/factory.py
Fixes #250 
Where build requests were piling up on slower builders because they were clean/don't clean/clean/ don't clean etc. and we could not merge those requests because of that difference.
Galina suggested that if we knew that the builder was going to clean the build first anyway, we could merge them. This commit implements that.
We do this by first setting a "clean" attribute on the builder's factory object, that we can find later via in the collapse callback.
So far only ClangBuilder passes this on but any builder can opt in by copying what it does.
In the collapse function when comparing properties we delete the "clean_obj" key from both sets of properties if we know that the builder's factory is always clean.
With some logging (not included in this commit) we can see it now …
=> Collapse clean and non clean build requests on clean builders

zorg/buildbot/builders/UnifiedTreeBuilder.py
Upstream buildbot releases error if a step name has over 50 characters long <https://github.com/buildbot/buildbot/issues/3414>. UnifiedTreeBuilder can produce quite long step names that violate this, meaning it's difficult to spin up a local test environment (as in <https://github.com/llvm/llvm-zorg/pull/289>) without local hacks to workaround this.
In this patch, we simply truncate step names at creation time. This means llvm-zorg's buildbot config can be used with an unmodified upstream buildbot package.
=> Prevent UnifiedTreeBuilder producing step names over 50 characters in length

buildbot/osuosl/master/config/builders.py
Reverts llvm/llvm-zorg#272
For https://github.com/llvm/llvm-project/issues/102513
Timeouts are back, but I didn't profile the build to check if the cause is the same file.
https://lab.llvm.org/buildbot/#/builders/107/builds/4901
=> Revert "Revert "[windows] Increase timeout for sanitizer-windows""

.github/workflows/lit-tests.yml
Installing a specific version of buildbot is more robust to future changes vs using whatever is packaged for Debian.
---
See here for an example of this working https://github.com/asb/llvm-zorg/actions/runs/11765732176/job/32772399920
I want to move over to this as a precursor to adding `buildbot checkconfig` to this flow, taking advantage of the local testing mode added in #289.
As a sidenote, the `run:` line can be changed to just `lit -v --xfail jenkins/test_build.py test` (as in the setup stage I'd added a symlink to allow this, but forgot to change the run line). I've left that change out of this PR to avoid changing two things at once, and as it's trivial I'd intend to just directly commit.
=> [GHA] Use pip and venv to install buildbot for lit tests

buildbot/osuosl/master/config/builders.py
To take advantage of https://github.com/llvm/llvm-zorg/pull/266. We use ccache on all our bots so this will not add much overhead.
The SVE bots are fast enough that the buildup of build requests is not really a problem, but for consistency I've marked them clean so all our 2 stage builds are clean.
=> Make Linaro 2 stage builders use clean builds

zorg/buildbot/builders/annotated/libc-linux.py
I just rekicked the cmake cache on the buildbots, which are now failing the
libc-scudo-integration-test ninja target with linker errors regarding undefined
reference to gwp_asan related symbols.
=> libc: add additional scudo cmake command line options

zorg/buildbot/builders/annotated/libc-linux.py
Prevent buildbots from building this target. If we remove AOR then we need to
spin the builds of it down first.
=> libc: stop building AOR

zorg/buildbot/builders/annotated/libc-linux.py
They're failing; not quite sure yet why.
Link: https://github.com/llvm/llvm-project/issues/116895
=> libc: disable scudo integration tests for now

zorg/buildbot/builders/annotated/libc-linux.py
Reverts llvm/llvm-zorg#315 since the issue should have been addressed.
=> Revert "libc: disable scudo integration tests for now"

buildbot/osuosl/master/config/builders.py
Pass missed environment variables also into the 2-nd stage of the builds.
=> Fix missed env vars for the 2-nd stage of the LLDB remote-linux builders.

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
Aside from the new CPU and different core/RAM amounts, these will be the same as our existing Gravition 3 ("g3") workers.
Builders to use these coming in a separate PR.
=> Add Linaro Graviton 4 workers

buildbot/osuosl/master/config/builders.py
These generate code that uses the SVE2 extension, as opposed to our existing builders that only use SVE. Therefore they will run on our Graviton 4 workers only, which are Neoverse v2 cores with SVE and SVE2.
The optimisation guide:
https://github.com/aws/aws-graviton-getting-started/blob/main/c-c++.md
Suggests -mcpu=neoverse-v2 for best performance, but here I'm using it just so we get the SVE2 feature enabled. If we used the balanced -mcpu=neoverse-512tvb, we wouldn't get SVE2 without fiddly extra flags.
```
$ ~/clang+llvm-18.1.8-aarch64-linux-gnu/bin/clang /tmp/test.c -o /dev/null -mcpu=neoverse-v2 -###
<...> "-target-feature" "+sve" "-target-feature" "+sve2-bitperm" "-target-feature" "+sve2" <...>
```
I have not added vector length settings as these builders will generate scalable …
=> Add AArch64 SVE2 Vector Length Agnostic builders

buildbot/osuosl/master/config/builders.py
As this is added by the build factories anyway.
Arm lldb has a thread limit so I've kept that in.
(this because the machine it runs on actually has a lot of headroom, but not all the time, so assuming you can always use every thread makes the results flaky)
=> Remove explicit LLVM_LIT_ARGS='-v' from Linaro builders

premerge/.gitignore, premerge/README.md, premerge/backend.tf, premerge/grafana_values.yaml, premerge/linux_container_pod_template.yaml, premerge/linux_runners_values.yaml, premerge/main.tf, premerge/metrics_deployment.yaml, premerge/vars.tf, premerge/windows_runner_values.yaml
This patch contains the terraform configuration for the premerge infrastructure. Actually applying changes requires someone from within Google with access to the GCP project to apply the changes, but the entire infrastructure is described within the TF in this patch.
Co-authored-by: Nathan Gauër <nathangauer@google.com>
=> [CI] Upstream terraform infrastructure

buildbot/osuosl/master/master.cfg
Ideally we'd better replicate the the deployed config, but this hopefully moves things forward. Note: as the GitHub Actions pre-commit testing relies on "local testing mode", this PR fixes that too.
@gkistanova the requirements.txt just references a local checkout for the buildbot version being used - the other libs are all 3.11.7 so that's what I use for the GitHub actions and the guidance for "local testing mode". Is there a public repo of the buildbot fork that is deployed?
=> Fix local testing mode by skipping downstream-only config setting

zorg/buildbot/builders/annotated/libc-linux.py
This was removed with the removal of "old" hdrgen in
https://github.com/llvm/llvm-project/pull/117220.
=> libc: remove libc-api-test

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
This patch is for a new builder for flang on powerpc64 AIX. This configuration has been tested on an internal buildbot master. I will follow up with @gkistanova via email to get the password exchange process started.
=> Add builder and worker for AIX ppc64 flang bot

buildbot/osuosl/master/config/builders.py
When running the llvm-test-suite, pass the C++ flags to the
Fortran compiler too, to check that it behaves correctly
with them.
=> Set Fortran flags on AArch64 SVE/SVE2 builders

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/status.py, zorg/buildbot/builders/annotated/libc-linux.py
Before renaming the existing debian-dbg-runtimes-build to
debian-dbg-bootstrap-build, make sure that the new name will be recognized so
that there's no downtime of CI coverage due to renaming the buildbot.
Also remove llvm from the explicit project list; that's not necessary (or may have
been for old hdrgen which has been removed).
Link: https://github.com/llvm/llvm-zorg/pull/325#discussion_r1870167521
=> libc: make new bootstrap builder a dup of runtimes

buildbot/osuosl/master/config/builders.py
Lnt was passing the flags with double quotes to cmake, which were
forwarded in this way to flang, making it parse them as a single
argument.
=> Fix quotes in Fortran flags on SVE/SVE2 builders

buildbot/osuosl/master/config/builders.py
The current config is unable to keep up with the load on that particular bot, meaning that the build queue filled-up and was at several hours. This reverts the introduced "neverCollapse" and does allow collapsing of build requests.
=> [AMDGPU][libc] Re-enable batching to keep up

zorg/buildbot/builders/annotated/libc-linux.py
No longer will any CI builds use LLVM_ENABLE_PROJECTS, which is deprecated as
of https://github.com/llvm/llvm-project/pull/117265.
Buildbots will probably need their CMakeCache.txt reset after this.
Link: https://github.com/llvm/llvm-project/issues/78479
=> libc: make all builds LLVM_ENABLE_RUNTIMES

zorg/buildbot/builders/annotated/libc-linux.py
=> libc: use runtimes dir as base for cmake

zorg/buildbot/builders/annotated/libc-linux.py
Link: https://github.com/llvm/llvm-project/issues/119789
=> libc: disable benchmarks to get fullbuilds back online

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
This adds a builder which is a clone of our existing llvm-clang-x86_64-gcc-ubuntu builder, except without assertions enabled. This is useful for finding tests that are added/updated but rely on (usually debug) information that isn't available when assertions are not enabled. This should help to catch those issues.
=> Add clone of llvm-clang-x86_64-gcc-ubuntu builder that builds without assertions.

buildbot/osuosl/master/config/builders.py
The reason for the change is to mitigate the failure during compiling when using Intel oneAPI product. 
The check from buildbot will prevent the commit to be merged if the job failed.
=> Extend avx512 win job with Intel oneAPI

zorg/buildbot/builders/SphinxDocsBuilder.py
Link: https://github.com/llvm/llvm-project/pull/120274
Link: https://github.com/llvm/llvm-project/pull/120319
=> sphinx: install requirements.txt

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py, zorg/buildbot/builders/annotated/amdgpu-offload-cmake.py
The buildbot uses the offload/cmake/cache/AMDGPUBot.cmake file to create the build config. It uses an annotated builder for that and only performs the build step as most of the post-commit issues are build problems and not test errors.
=> [Offload] Adds buildbot for CMake cache file

buildbot/osuosl/master/config/builders.py
When I originally adder this builder, I'm not sure why I changed the linker to be lld, it should be gold to match our previous instance. This change fixes that.
=> Change linker from lld to gold for builder.

buildbot/osuosl/master/config/builders.py
API tests llvm-project/lldb/test/API/tools/lldb-server/* with the category `lldb-server` run lldb-server locally on the host with a random port. Sometimes we got errors like
https://lab.llvm.org/buildbot/#/builders/195/builds/3145
https://lab.llvm.org/buildbot/#/builders/197/builds/312
The patch https://github.com/llvm/llvm-project/pull/118222 improved the situation but did not fix it completely.
=> Disable the test category `lldb-server` for lldb-remote-* builders

buildbot/osuosl/master/config/builders.py
This reflects the host hardware, rather than the limited subset of features on the Cortex-A57.
```
$ lscpu
Architecture:            aarch64
CPU op-mode(s):        32-bit, 64-bit
<...>
Vendor ID:               ARM
Model name:            Neoverse-N1
<...>
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid
asimdrdm lrcpc dcpop asimddp
```
I have also confirmed that the Neoverse V1 (Note: V not N) that is used for Graviton is a superset of these features.
https://github.com/aws/aws-graviton-getting-started/blob/main/c-c%2B%2B.md#enabling-arm-architecture-specific-features
So if we have to move these builds to Graviton 3 at short notice, this will still work (Graviton 4 also ok for AArch64, but it drops the AArch32 mode).
=> Compile for Neoverse N1 on Linaro's Armv8 bots that are on Mt Jade hardware

tasks/cmake/caches/util/xcode_sdk.cmake
After the update of the Cmake binary on our CI fleet, the way Cmake handles internal processes has changed and we need to explicitly set the shebang on our wrapper shims to avoid 
```
Error running link command: Unknown system error -8
```
=> [CI] Add shebang to shim wrapper scripts

tasks/lnt-testsuite.dep
We no longer install cmake from brew on our CI
=> [LNT] Remove brew cmake check

buildbot/fuchsia/Dockerfile
The Fuchsia toolchain normally builds with FatLTO, and the existing llvm-17 toolchain does not properly support FatLTO compilation. The 17 release does have a FatLTO pipeline, but frontend support in clang was not ready in time for the llvm-17 release.
=> [fuchsia] Use llvm-19 on Fuchsia bots

buildbot/osuosl/master/config/builders.py
allow collapseRequests for flang AIX bot: https://lab.llvm.org/buildbot/#/builders/201, due to a long build queue. Most aix bots already allow collapseRequests so this would be consistent with existing behaviour.
=> Collapse requests for the flang AIX buildbot

zorg/jenkins/jobs/jobs/clang-stage2-cmake-RgSan
This will keep the job from hanging if it encounters any spurious infrastructure issues
=> Set timeout to 12 hours for clang-stage2-cmake-RgSan

zorg/buildbot/builders/annotated/amdgpu-offload-cmake.py
We need to clean the build directory to take changes to the CMake cache file have any effect for the actual build config.
=> [AMDGPU] Fix CMake cache builder

zorg/buildbot/builders/annotated/amdgpu-offload-cmake.py
We want to clean the build directory in order for changes to the in-tree CMake cache file to take effect. Otherwise the local config takes precedence.
=> [AMDGPU][Offload] Clean CMake to let updates take effect

premerge/architecture.md
arguably we should rename the file instead for consistency, but I'm not quite ready to attempt that yet :)
=> [CI] Fix broken link in architecture.md

buildbot/osuosl/master/config/builders.py, zorg/buildbot/builders/annotated/rise-riscv-build.sh
The intent is for the rest of the RISE RISC-V builders to follow, but this starts the process.
Previously the builders used the framework provided by ClangBuilder.py. As the build has required more customisation (with more to come - such as building the llvm-test-suite with the stage1 compiler which isn't support by ClangBuilder) this is requiring more and more changes to increase configurability of ClangBuilder, but this makes the logic harder to follow and I think we've reached the limit of what's reasonable.
The AnnotatedBuilder infrastructure allows the build logic to just be put in a shell script. The latest version of llvm-zorg is checked out and the script is executed. This has the additional advantage of decoupling script updates from needing to wait for buildmaster redeploys. …
=> [RISCV] Move clang-riscv-rva23-evl-vec-2stage to annotated builder

buildbot/osuosl/master/config/builders.py, zorg/buildbot/builders/annotated/rise-riscv-build.sh
Followup to #374 (and stacks on top of it), but this time converting the RVA20 builder.
=> [RISCV] Move clang-riscv-rva20-2stage to annotated builder

buildbot/osuosl/master/config/builders.py, zorg/buildbot/builders/annotated/rise-riscv-build.sh
As noted in the inline TODO, it may be worth later changing this so the
test suite is run immediately after stage1 as stage1 + llvm-test-suite
can build and run very quickly, provided rapid feedback.
Although the lit-on-qemu mechanism could be used to run the test suite
under qemu-system, we instead run the test suite under qemu-user. This
has the advantage of simplicity - the suite runs well in this mode and
we don't have the same concerns about testing things that may not work
under qemu-user (such as LLDB or sanitizers) as for the main
llvm-project tests.
=> [RISCV] Add llvm-test-suite to RISC-V annotated builders

buildbot/osuosl/master/config/builders.py
Remove running offload tests on this machine, given that there might be something wrong more fundamentally.
=> [AMDGPU] Remove flaky offload tests from builder

buildbot/osuosl/master/config/builders.py
Gentle increase to the number of GPU tests run in parallel on the device. Tested this locally, this should be a reasonable balance between speed up and system load.
=> [AMDGPU][Libc] Four parallel GPU processes

buildbot/osuosl/master/config/builders.py, zorg/buildbot/process/factory.py
While #333 tried to update all buildbots all at once, this starts with updating just one buildbot to test the `LLVM_ENABLE_RUNTIMES=flang-rt` configuration.
The builder is currently running in staging here: https://lab.llvm.org/staging/#/builders/36
=> Enable LLVM_ENABLE_RUNTIMES build of Flang-RT for flang-x86_64-windows

buildbot/osuosl/master/config/builders.py
Add `depends_on_projects=['flang-rt']`, and `checks=['check-flang-rt']` to the ppc64-flang-aix builder. The prepares the removal of the "projects" build of the flang runtime in https://github.com/llvm/llvm-project/pull/124126.
Split off from #333
Affected builders:
* ppc64-flang-aix
Affected workers:
* ppc64-flang-aix-test (production)
Admins listed for those workers:
* LLVM on Power <powerllvm@ca.ibm.com>
* Mark Danial <mark.danial@ibm.com>
=> LLVM_ENABLE_RUNTIMES=flang-rt for ppc64-flang-aix

buildbot/osuosl/master/config/builders.py
Specify LLVM_PTXAS_EXECUTABLE environment variable with a full path to 'ptxas' tool from installed NVIDIA CUDA Toolkit. LIT will be automatically check and use this tool to validate PTX during the tests.
=> Allow Lit to use 'ptxas' tool to validate generated PTX on the NVPTX builders.

buildbot/osuosl/master/config/status.py
These have been moved to production more or less recently, make them send email to the maintainers when they fail.
=> [AMDGPU] Make builders send emails to maintainer

buildbot/osuosl/master/config/builders.py
Add `depends_on_projects=['flang-rt']` and `checks=['check-flang-rt']` to Linaro's builders that are based on UnifiedTreeBuilder. This prepares the removal of the "projects" build of the flang runtime in https://github.com/llvm/llvm-project/pull/124126.
Split off from #333
Affected builders:
* flang-aarch64-dylib
* flang-aarch64-sharedlibs
* flang-aarch64-debug-reverse-iteration
* flang-aarch64-libcxx
* flang-aarch64-release
* flang-aarch64-rel-assert
* flang-aarch64-latest-gcc
Affected workers:
* linaro-flang-aarch64-dylib
* linaro-flang-aarch64-sharedlibs
* linaro-flang-aarch64-debug-reverse-iteration
* linaro-flang-aarch64-libcxx
* linaro-flang-aarch64-release
* linaro-flang-aarch64-rel-assert
* linaro-flang-aarch64-latest-gcc
I could locally confirm that `flang-aarch64-dylib` works on …
=> LLVM_ENABLE_RUNTIMES=flang-rt for UnifiedTreeBuilder builders

buildbot/osuosl/master/config/builders.py
Since 0ac8f9de5a08472260e0e532123b35feb095114c, [openmp-offload-amdgpu-clang-flang](https://lab.llvm.org/staging/#/builders/105/builds/16994) is failing with
```
CMake Error at /home/botworker/builds/openmp-offload-amdgpu-clang-flang/llvm.src/flang-rt/lib/quadmath/CMakeLists.txt:85 (message):
FLANG_RUNTIME_F128_MATH_LIB setting requires quadmath.h to be available:
libquadmath
```
The reason is that flang-rt now is built using Clang (like all LLVM runtimes in a bootstrapping build), instead of gcc. `quadmath.h` is located in gcc's "resource dir" (on my system, it is `/usr/lib/gcc/x86_64-linux-gnu/13/include/quadmath.h`) instead in default paths such as `/usr/include`. Hence, clang cannot find it.
Remove the `FLANG_RUNTIME_F128_MATH_LIB=libquadmath` option since by design it does not work …
=> Fix openmp-offload-amdgpu-clang-flang

zorg/buildbot/builders/ClangBuilder.py
With the option `checkout_flang=True`, ClangBuilder-based builders also compile Flang. Modify ClangBuilder to use `LLVM_ENABLE_RUNTIMES=flang-rt`. This prepares the removal of the "projects" build of the flang runtime in https://github.com/llvm/llvm-project/pull/124126.
Split off from #333
Affected builders:
* clang-aarch64-full-2stage
* clang-aarch64-sve-vla
* clang-aarch64-sve-vla-2stage
* clang-aarch64-sve-vls
* clang-aarch64-sve-vls-2stage
* clang-aarch64-sve2-vla
* clang-aarch64-sve2-vla-2stage
* clang-arm64-windows-msvc
* clang-arm64-windows-msvc-2stage
Affected workers:
* linaro-clang-aarch64-full-2stage
* linaro-g3-01
* linaro-g3-02
* linaro-g3-03
* linaro-g3-04
* linaro-g4-01
* linaro-g4-02
* linaro-armv8-windows-msvc-04
* linaro-armv8-windows-msvc-02
Admins listed for those …
=> LLVM_ENABLE_RUNTIMES=flang-rt for ClangBuilder builders

buildbot/osuosl/master/config/builders.py
Add `depends_on_projects=['flang-rt']`, and `checks=['check-flang-rt']` to the ppc64le-flang-rhel-clang builder. The prepares the removal of the "projects" build of the flang runtime in https://github.com/llvm/llvm-project/pull/124126.
The corresponding change in the LLVM repository is https://github.com/llvm/llvm-project/pull/129692
Affected builders (production):
* [amdgpu-offload-ubuntu-22-cmake-build-only](https://lab.llvm.org/buildbot/#/builders/203)
* [amdgpu-offload-rhel-9-cmake-build-only](https://lab.llvm.org/buildbot/#/builders/205)
* [amdgpu-offload-rhel-8-cmake-build-only](https://lab.llvm.org/buildbot/#/builders/204)
Affected workers (production):
* [rocm-docker-ubu-22](https://lab.llvm.org/buildbot/#/workers/162)
* [rocm-docker-rhel-9](https://lab.llvm.org/buildbot/#/workers/ …
=> LLVM_ENABLE_RUNTIMES=flang-rt for amdgpu-offload-*

buildbot/osuosl/master/config/builders.py
Add `depends_on_projects=['flang-rt']`, and `checks=['check-flang-rt']` to the ppc64le-flang-rhel-clang builder. The prepares the removal of the "projects" build of the flang runtime in https://github.com/llvm/llvm-project/pull/124126.
Split off from #333
Affected builders:
* [ppc64le-flang-rhel-clang](https://lab.llvm.org/buildbot/#/builders/157)
Affected workers:
* [ppc64le-flang-rhel-test](https://lab.llvm.org/buildbot/#/workers/152) (production)
Admins listed for those workers:
* LLVM on Power <powerllvm@ca.ibm.com>
=> LLVM_ENABLE_RUNTIMES=flang-rt for ppc64le-flang-rhel-clang

buildbot/osuosl/master/config/builders.py
Update premerge-monolithic-windows and premerge-monolithic-linux to prepare for the removal of the "projects" build of the flang runtime in https://github.com/llvm/llvm-project/pull/124126.
This does not change the actual premerge GitHub action, which is done by https://github.com/llvm/llvm-project/pull/128678
For premerge-monolithic-linux, add flang-rt to the LLVM_ENABLE_RUNTIMES list, indirectly by adding it to `depends_on_projects` which also updated the build scheduler.
For premerge-monolithic-windows, remove building flang to match the actual pre-merge build which disabled building flang on Windows in https://github.com/llvm/llvm-project/commit/e4b424afc4fbfe31ea1876114b4e9232efbf2297. Adding flang-rt would also require compiler-rt (which was always required on Windows, but now there …
=> LLVM_ENABLE_RUNTIMES=flang-rt for premerge-monolithic-*

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
This patch introduces a dedicated flang-arm64-windows-msvc buildbot to decouple Flang from the existing Clang buildbot splitting load.
This will test flang with openmp and flang-rt runtimes and will run check-mlir, check-flang, and check-flang-rt.
=> Add flang-arm64-windows-msvc buildbot

buildbot/osuosl/master/config/builders.py, zorg/buildbot/builders/FlangBuilder.py, zorg/buildbot/builders/UnifiedTreeBuilder.py, zorg/buildbot/process/factory.py
Make `FlangBuilder.getFlangOutOfTreeBuildFactory` build the flang-rt runtime as an out-of-tree runtimes build with additional steps.
Fixes some issues with FlangBuilder too:
* Clears the build directories with the clean_obj flag set. Usually buildbot deletes the build directory whenever a CMakeLists.txt in a depends_on_projects subdirectory changes to get a clean build. Otherwise, an incompatible CMakeCache.txt will carry on forever.
* Add `flang` and `flang-rt` as depends_on_projects. Otherwise, changes in these subdirectories do not trigger a build. Even worse, breaking commits will be attributed to the next commit in llvm/clang/mlir/openmp, as happed in e.g. https://lab.llvm.org/buildbot/#/builders/53/builds/11759 (commit causing failure was …
=> LLVM_ENABLE_RUNTIMES=flang-rt for flang-aarch64-out-of-tree

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py, zorg/buildbot/builders/annotated/hip-tpl.py
This adds:
- Builder for HIP-enabled Kokkos library build+test
- Worker for that builder
- Script for AnnotatedBuilder to build third-party libraries
This increases HIP test coverage substantially in the upstream and helps to identify issues earlier.
Initially, this will contain only Kokkos.
The Ginkgo library is lined up and will be added next.
=> [HIP] Builder for third-party libraries (Kokkos first)

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/status.py, buildbot/osuosl/master/config/workers.py
This change adds a new fast linux builder that targets the PS5 (our current fast builder targets PS4), updates the list of bots I am notified about for failures and updates some worker descriptions.
=> Add fast ps5 linux builder, update my build failure notifications and update some descriptions.

buildbot/osuosl/master/config/builders.py
This is a follow up patch from #398 and it removes Flang from the clang-arm64-windows-msvc builder.
This patch also introduces the following changes to clang-arm64-windows-msvc:
1) Switches to UnifiedTreeBuilder
2) Enables LLVM_ENABLE_RUNTIMES=compiler-rt;openmp
3) Restricts DLLVM_TARGETS_TO_BUILD to AArch64, ARM, and X86
=> Decouple Flang from WoA clang  buildbot

buildbot/osuosl/master/config/builders.py
The option was removed in #395. After https://github.com/llvm/llvm-project/pull/130411, the option should now work even when compiling flang-rt with Clang.
=> [openmp-offload-amdgpu-clang-flang] Re-add FLANG_RUNTIME_F128_MATH_LIB

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/status.py, buildbot/osuosl/master/config/workers.py
- Adds a new builder llvm-clang-key-instructions
- Adds a new worker sie-linux-worker5
- Removes a no longer needed Mail Notifier for a decomissioned builder
- Adds email notification to myself and Orlando for the new key instructions build bot
=> Add a new build bot to test key instructions feature.

buildbot/osuosl/master/config/builders.py
The containerized runner is executing on a certain CPU set. This seems to confuse the specific test and makes it fail.
xfail it therefore.
=> [AMDGPU] Adjust xfail tests

zorg/jenkins/jobs/jobs/lldb-cmake-matrix, zorg/jenkins/jobs/jobs/lldb-cmake-sanitized
Update lldb-matrix and lldb-sanitized to run on apple SI machines
=> Update lldb jobs to run on arm 64 machines

buildbot/osuosl/master/config/builders.py
llvm/llvm-project#129012 added a new CMake flag. This flag is used by IBM's downstream builds.
This patch sets the flag on the community buildbot for AIX to ensure upstream coverage and visibility.
=> AIX: Default SANITIZER_DISABLE_SYMBOLIZER_PATH_SEARCH to ON

premerge/main.tf
The version was fixed, which prevents us from updating the secret in one step.
PAT token was about to expire, needed regen.
=> presubmit: remove version fix on github PAT secret

premerge/cluster-management.md
Upgrading/resetting ARC is a somewhat involved process that cannot be done with
just terraform apply with an updated configuration. This patch adds some
documentation on the exact steps to perform, some of the motivation behind
them, and some tips and tricks that I have developed while hacking on the
cluster.
=> Add documentation on resetting ARC

premerge/linux_runners_values.yaml
We recently bumped the CI container from Ubuntu 22.04 to 24.04 in the monorepo. This patch bumps the version here to keep up with the updates, especially given that the bump means the 22.04 version is not really supported/maintained upstream anymore.
=> [CI] Bump CI Container Version

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py, zorg/buildbot/builders/annotated/rise-riscv-gauntlet-build.sh
More so than the other RISC-V builders, this is optimised for getting some testing feedback as quickly as possible. It isn't intended to replace any of those, meaning we can rely on them still running for higher coverage and higher emulation fidelity. The idea of this bot is to help with the steps we typically end up taking if there's an unexpected bot failure:
* Figure out if it's easily reproducible on a simple test (especially true if there was an issue in a stage2 native build).
* Determine if it affects all or only some configurations.
* Narrow down exactly which patch caused it (helped here due to more rapid cycle time of this bot).
It does this by doing a simple stage1 build, then cross-compiling the llvm-test-suite in multiple configurations and running with qemu-user. It takes …
=> [RISCV] Add "gauntlet" bot for rapidly testing a range of configs with llvm-test-suite

buildbot/fuchsia/Dockerfile
The CMake 4.0 no longer allow adding a shared library target when
the target platform is a baremetal platform. This change downgrades
the cmake from 4.0 to jammy release (3.22) to mitigate this issue.
=> [fuchsia] Downgrade cmake from latest to release from Ubuntu jammy

buildbot/fuchsia/Dockerfile
This is required by llvm-mt as of
https://github.com/llvm/llvm-project/pull/134631.
=> [Fuchsia] Install libxml2 development package

buildbot/osuosl/master/config/builders.py
https://discourse.llvm.org/t/possible-issue-with-premerge-monolithic-windows/86070 showed some issues due to a dirty cache. We should be cleaning the build directory after each build and letting sccache handle all of the caching
This is for the old infrastructure which should be turned down in a couple weeks, but it's a simple enough patch in the mean time.
=> Clean build directory in cmake monolithic windows

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/release_builders.py
Add "--timeout=900" to our bots to prevent a hanging test from causing the entire testing step from hanging (for example https://lab.llvm.org/buildbot/#/builders/174/builds/16853). It was suggested that I could add this argument to prevent the problem from happening.
=> Add "--timeout=900" to builders to avoid hanging tests from causing testing to hang.

premerge/gke_cluster/main.tf, premerge/gke_cluster/outputs.tf, premerge/gke_cluster/variables.tf, premerge/main.tf
This patch refactors GKE cluster creation into a module. This enables reuse
later on when we want to create a new cluster in a different region for a
HA setup.
=> [CI] Refactor GKE cluster creation into a module

premerge/main.tf
This makes things a bit more consistent in preparation for setting up
another cluster.
=> [CI] Rename premerge cluster in preparation for HA

premerge/cluster-management.md
This patch updates the cluster management documentation now that we have renamed the llvm-premerge-prototype cluster to llvm-premerge-cluster-us-central.
=> [CI] Update docs after renaming of llvm-premerge-prototype

buildbot/osuosl/master/config/builders.py
Use clean builds for the s390x multistage builder as was done for Linaro in https://github.com/llvm/llvm-zorg/pull/306.  This will enable collapsing build requests to help the builder keep up.
As further speed-up, skip the stage 1 testing, as is already done for most other multistage builders.
=> [s390x] Make stage 2 builder use clean builds

zorg/jenkins/jobs/jobs/clang-stage1-RA
There are recent timeouts for 90min. Extend the timeout to make sure the job can finish.
=> [GreenDragon] Bump Clang Stage 1 RA Build timeout to 120min

tasks/utils/lnt_submit.sh
Skip LNT submission so that the jobs aren't reporting failure status. There is not a stable LNT server setup as of right now
This will allow us to at least get build status from the green dragon LNT jobs
=> Skip LNT submission

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/release_builders.py
* switch to clang-21/lld-21 instead of gcc/ld.gold to speed up the builds and avoid the ld.gold liner warnings related with unsupported DWARF version.
* switch to release build to speed up the builds because of clang/llvm table-gen tool.
Also moved to 'UnifiedTreeBuilder.getCmakeExBuildFactory' factory.
=> Update configuration for llvm-clang-x86_64-expensive-checks-ubuntu* builders

premerge/gke_cluster/main.tf, premerge/gke_cluster/variables.tf, premerge/main.tf
This migrates the other windows node pool in us-central1-a to pd-ssd boot disks as well. We saw some small performance improvements from doing this (~5%). Less than expected, but significant enough to ship.
=> [CI] Migrate all windows node pools to pd-ssd

zorg/jenkins/build.py, zorg/jenkins/jobs/jobs/clang-stage2-cmake-RgSan
`fsanitizer.c` test from clang sometimes hits the individial tests timeout on ASAN + UBSAN bot. Increase the timeout for lit on the bot. Also prints slow tests time on all Darwin bots.
=> [GreenDragon] Extend lit timeout for sanitizer bot

zorg/buildbot/reporters/utils.py
This small PR fixes the message formatting in `zorg/buildbot/reporters/utils.py`.
=> Fix message formatting

premerge/main.tf, premerge/metrics_deployment.yaml
Now that buildkite has been sunsetted, we no longer need to keep track of the Buildkite workflows. https://github.com/llvm/llvm-project/pull/143049 does this on the metrics container side. This patch adjusts the deployment to those changes. Note that patch needs to land first before this can be applied.
=> [CI] Remove Buildkite Token from metrics container

buildbot/osuosl/master/config/builders.py
There's nothing wrong with the latter - except that LLVM_CCACHE_BUILD knows that it should not be enabling pre-compiled headers on Windows.
See https://github.com/llvm/llvm-project/pull/136856
We had a contributor report an issue with this, and it only got fixed when someone randomly managed to update the right files for an unrelated change.
```
/Fdtools\flang\lib\Parser\CMakeFiles\FortranParser.dir\FortranParser.pdb
-c -- C:/Users/tcwg/llvm-worker/flang-arm64-windows-msvc/llvm-project/flang/lib/Parser/preprocessor.cpp
fatal error: file
'C:\Users\tcwg\llvm-worker\flang-arm64-windows-msvc\llvm-project\llvm\include\llvm\Support\Compiler.h'
has been modified since the precompiled header
'C:/Users/tcwg/llvm-worker/flang-arm64-windows-msvc/build/tools/flang/lib/Parser/CMakeFiles/FortranParser.d …
```
=> Linaro / Windows: Use LLVM_CCACHE_BUILD instead of CMAKE_CXX_COMPILER_LAUNCHER

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py, zorg/buildbot/builders/annotated/rise-riscv-build.sh
This adds:
* rva23 with zvl512b
* rva23 with zvl1024b
* -mcpu=spacemit-x60 with -mrvv-vector-bits=zvl (this config also gives zvl256b coverage)
=> [RISCV] Add additional RISC-V 2-stage cross-compile and test under qemu-system configs

zorg/buildbot/builders/UnifiedTreeBuilder.py
The default value for checks in addNinjaSteps is None. This patch adds the check steps only when they are not None.
=> Handle None checks in UnifiedTreeBuilder.addNinjaSteps

zorg/buildbot/builders/BOLTBuilder.py
If in-tree tests do not run, mark the whole build as skipped. Note that when this happens, out-of-tree tests also do not run.
This helps when navigating Buildbot's build requests:
- Skipped builds indicate the change was unrelated to BOLT.
- Any other errors are still reported.
- For breaking changes that need reversal, builds will show as SKIPPED or FAILURE depending on whether llvm-bolt was affected, instead of SUCCESS or FAILURE, which can be confusing.
=> [BOLT] Mark build skipped when tests did not run

zorg/buildbot/builders/BOLTBuilder.py
Some patches can cause the llvm-bolt binary to hang, which stalls or fails the test pipeline.
Add a simple sanity check that runs:
```
llvm-bolt --version
```
with a 30-second timeout. If the command does not complete in time, flunk the build.
Also, sets maxTime for nfc-check-validation and reduce the number of lit workers for in-tree tests.
=> [BOLT] Add sanity check for frozen llvm-bolt

premerge/gke_cluster/main.tf, premerge/linux_runners_values.yaml
This patch doubles the Linux Runner Counts from 8 per cluster to 16 per cluster for a total of 32. We recently were able to get some more quota to allow for this.
=> [CI] Double Linux Runner Counts

zorg/buildbot/builders/annotated/amdgpu-offload-cmake.py, zorg/buildbot/builders/annotated/rise-riscv-build.sh, zorg/buildbot/builders/annotated/rise-riscv-gauntlet-build.sh
This patch version pins providers and bumps the google provider to
v6.43.0. We need to bump the Google provider so that we can set the windows OS
version on windows node pools for the switch to server 2022. This also pins
some other providers as hashicorp/helm in particular has breaking changes in v3
which terraform init -upgrade will install before this patch.
=> [CI] Version pin providers

buildbot/google/terraform/main.tf, buildbot/google/terraform/variables.tf
Run terraform fmt -recursive . across the whole repository. A couple
buildbot/google files get formatted during this process.
=> Format all terraform files

premerge/architecture.md, premerge/cluster-management.md
There are a couple places where we need to update the documentation to reflect
changes made due to the introduction of the libc++ runner sets. I did a cursory
glance through the documentation and updated everything where I saw something
was incorrect, but this patch might not be exhaustive.
=> [CI] Update documentation after libcxx runner sets

premerge/gke_cluster/main.tf
This patch sets up GCS Buckets for sccache remote caching. We set up one for
Linux and one for Windows in each cluster. This creates some separation which
might help slightly with security. We want to have the buckets in the same
region as the machines to ensure uploads/downloads are as low latency as
possible which is helped significantly when the compute and storage are
colocated.
=> [CI] Setup Buckets for Sccache

premerge/linux_runners_values.yaml, premerge/premerge_resources/main.tf, premerge/windows_2022_runner_values.yaml
This patch passes the per-cluster bucket names through to the runner pods in a custom env variable. This allows for configuring sccache inside the workflow to use the GCS buckets.
=> [CI] Pass Bucket Names Through to Runner Pods

llvm-ops-metrics/ops-container/process_llvm_commits.py
Originally, the script for scraping LLVM commit info required persistent storage to keep track of the last commit we've seen. This was to prevent any overlap in our scrapes and avoid processing the same commits multiple times.  
However, currently the script will only ever scrape a full day at a time, so there should never be any overlap. We no longer need persistent storage to maintain the most recently viewed commits since we don't expect the CronJob to be executed twice in the same day.
=> [CI] Remove need for operational metrics persistent storage

premerge/gke_cluster/main.tf, premerge/main.tf, premerge/operational_metrics_cronjob.yaml
These resources are for a CronJob that executes the container at `ghcr.io/llvm/operations-metrics:latest` on a daily basis (07:00 UTC), which will scrape daily metrics regarding LLVM's commit volume and upload them for visualization in Grafana.
Changes were made to the already existing terraform files since many of the same resources are being reused anyway. This way we can keep all relevant changes in the same place instead of having two separate terraform directories that access and modify shared resources.
Since the container needs access to the BigQuery Google Cloud API, IAM and K8S service accounts were used to grant that access via Workload Identity Federation for GKE. More details at https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
=> [CI] Add Terraform resources for daily CronJob that processes LLVM commits

premerge/linux_runners_values.yaml, premerge/windows_2022_runner_values.yaml
This patch adds lifecycle rules to the GCS buckets to delete old objects.
We do not want to keep object files around for very long as they quickly
become out of date. GCS does not keep track of the last time a file was
fetched, so we have to rely on the creation date. The granularity for when
to delete an object can only be specified in days, so we set it to one
day for now.
=> [CI] Add Lifecycle Rules to GCS Buckets

buildbot/osuosl/master/config/status.py
Currently the email notifications go to my work address, but since some of the bots I manage are self-hosted, it would be useful to get notifications to a personal email so I don't have to check my work email to see them. This adds a personal email so that I can get notifications there as well of problems.
=> Add another email to the list of notifications for my bots.

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
This removes the single stage test suite bot, then adds stage 1 check and final test suite run to the 2 stage bot.
Which is the equivalent but 1 fewer worker. It'll slow down the 2 stage builds a bit but there's no a lot of activity in the 32-bit Arm area anyway, so I don't think it's a problem.
=> Merge clang-armv7-lnt into clang-armv7-2stage

premerge/gke_cluster/main.tf
This patch adds an explicit maintenance window to the premerge clusters. This is in response to some control plane upgrades that we recieved notice of that will prevent access to the k8s control plane for ~15 minutes which means we will not be able to start new jobs. We should have this anyways though as the current node upgrade strategy also breaks jobs.
=> [CI] Add maintenance window to premerge clusters

llvm-ops-metrics/ops-container/process_llvm_commits.py
As GitHubArchive BigQuery is known to be lossy, it is likely that we currently overestimate the number of commits made to llvm/llvm-project without an associated pull request.
To remedy this, we can make calls to the [GitHub Event API](https://docs.github.com/en/rest/activity/events). While we want to avoid using the API to get information regarding every single commit made to LLVM, we can narrow our calls down to only commits that don't have any pull request data available via BigQuery. From those calls, we can determine if a "push" commit actually does have a pull request and, if it does, whether or not it has been approved.
=> [CI] Validate scraped push commits via GitHub API

zorg/jenkins/jobs/jobs/clang-stage1-RA-as
Add clang-stage1-RA-as job which runs on arm64 machines
=> Add Stage 1 arm 64 job

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/status.py, buildbot/osuosl/master/config/workers.py
This patch removes the old LLVM premerge bots from llvm-zorg in preparation
for adding in the new ones.
=> [CI] Remove old premerge bots

premerge/buildbot/dispatch_job.py
This script should be used directly as an annotated builder and this script sets
it up to do so. There are two main changes:
1. We print out a build step command. The monolithic scripts will eventually need
to be upgraded to print out more fine grained build step information.
2. We take in a BUILDBOT_REVISION rather than the SHA on the command line.
Passing the commit SHA along on the command line is complicated while
BUILDBOT_REVISION is set by default for all annotated builders.
=> [CI] Convert dispatch_jobs.py into an annotated builder

premerge/cluster-management.md
Adding documentation about usage of Grafana Cloud tokens in the infra, and how to rotate them if required.
=> [CI] Update documentation about token rotation

premerge/premerge_resources/variables.tf
After https://github.com/llvm/llvm-project/pull/153035 we have a new runner image that should theoretically work. Set the next runner set to use it so we can start testing.
=> [CI] Bump libcxx next runner image to 77cb09

premerge/gke_cluster/main.tf
Currently we delete cached build artifacts after one day. This patch bumps that to seven days. We are using very little storage currently (15-20GB) per bucket, so bumping this should have a negligible impact on cost. This also allows for builds that are not run as often (like those on the release branch) to have a warm cache when they are run again, assuming they are run at a reasonable cadence.
=> [CI] Bump Object Age at Deletion to 7 Days

zorg/buildbot/builders/annotated/hip-build.sh
It slipped my attention that this builder was (still?) doing incremental builds. This is highly not recommended by the community.
This patch nukes an existing build dir completely to start from a clean state and rely on ccache to bring build-time improvements.
=> [HIP] Prefer ccache over incremental build

premerge/buildbot_deployment.yaml, premerge/gke_cluster/main.tf, premerge/premerge_resources/main.tf
Add all of the service accounts/IAM bindings needed for GCS caching in the
buildbot namespaces. Use separate service accounts in case we want to
restrict the permissions between the PR checks and postcommit buildbots
differently.
=> [CI] Terraform Plumbing for GCS Caching in Buildbot

premerge/premerge_resources/variables.tf, zorg/buildbot/builders/annotated/hip-build.sh
Now that we have buckets available and plumbed through terraform, setup
dispatch_job.py to actually setup sccache so the build scripts will use
the remote cache.
=> [CI] Update dispatch_job.py to setup sccache

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/status.py
We no longer need the Key Instructions builder, so this change removes it, and reassigns the worker to a new Debugify builder that is being added. Additionally this removes the notifications for the old builder and adds new ones for the new builder.
This change depends on #493.
=> Remove Key Instruction builder and add a new Debugify builder

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
The original intention for the premerge workers was that they could handle multiple builds at the same time. However, buildbot does not support a worker running more than one job at a time for a single builder, which is how we have things setup. Switch to having three builders per platform per cluster rather than one builder with max_builders set to 3.
=> [CI] Add more premerge buildbot workers

premerge/main.tf
This change makes it so the `bigquery.jobUser` role can be granted to new members while preserving grants for past members. `google_project_iam_binding` is authoritative, and revokes role access for all other members who are not listed in the resource definition when running `terraform apply`. This is problematic as we now have another internal service account that needs access to `role/bigquery.jobUser`, and it's membership will continue to be revoked as long as we define a binding here.
=> [CI] Use iam_member instead of iam_binding for BQ JobUser role

buildbot/osuosl/master/config/builders.py, zorg/buildbot/builders/annotated/profcheck.sh
This allows setting the LIT_XFAIL environment variable before running ninja which enables excluding tests from a file in the LLVM tree. I do not believe this is possible outside of an annotated builder.
=> [ProfCheck] Switch to annotated builder

buildbot/osuosl/master/config/status.py, buildbot/osuosl/master/config/workers.py
This is so that the appropriate people are getting notifications when there are failures related to the premerge buildbots. Most of the time no action is needed as build failures happen reasonably often and are usually fixed quickly. Having the notifications (especially for missing workers) helps ensure that the infra is not down/broken for a while.
Currently adding the premerge rotation, myself and Caroline. We might eventually want to only have the premerge rotation on this, but as we stabilize the infrastructure, having more people get notifications should be helpful.
=> [CI] Add notifications for premerge buildbots

buildbot/osuosl/master/config/builders.py
The builder builds host based BOLT tools only, no Aarch64 bolt runtime yet (not supported for the cross toolchain builds).
=> Enable BOLT project on Aarch64/Linux Windows host cross builder.

buildbot/osuosl/master/config/builders.py
Add additional dependencies with the libc++/libc++abi/libunwind and compiler-rt libraries.
Also removed unaffected LLDB_CAN_USE_LLDB_SERVER options.
=> Update the project dependencies for the lldb-remote-linux builders.

buildbot/osuosl/master/config/builders.py
Move the buildbot that used to do the libc builds to the CMake cache file based approach.
This is a bit of a WIP as we also sort out a few other things in the background.
=> [AMDGPU][Libc] Add cmake-cache based builder

buildbot/osuosl/master/config/builders.py, buildbot/osuosl/master/config/workers.py
This PR adds a new buildbot to run LLVM testsuite on windows. It adds a new builder and worker pair. The testsuite will run after the first stage build skipping the ninja check step as we cover that on other buildbots. This will primarily be the builder to test that ensures LNT and LLVM testsuite are running without regressions on windows. We will later build on it to add support for test more as our Windows hardware availability improves.
This depends on #575 and llvm/llvm-project#155226.
=> Add flang-arm64-windows-msvc-testsuite builder

zorg/buildbot/builders/annotated/premerge/dispatch_job.py
This patch ensures we test flang-rt postcommit so we are actually testing the configuration introduced by #156039.
=> [CI] Add flang-rt to postcommit testing

buildbot/osuosl/master/config/builders.py
Having the argument as part of the script name is an error as it tries to find / exec that exact string.
Pass theargument as extra_args instead. Not sure if we need to split argument name and value in separate array entries.
=> [AMDGPU][Libc] Fix argument passing to script

buildbot/osuosl/master/config/workers.py
Update descriptions for several bots that were no longer accurate.
Also remove jobs properties on two of the MacOS builders to not be hardcoded.
=> Update configurations for Mac builders as well as comment descriptions for a few bots.

zorg/buildbot/builders/UnifiedTreeBuilder.py
Added missed 'enable_projects' argument for UnifiedTreeBuilder.getCmakeExBuildFactory
to pass it to the base LLVMBuildFactory class.
=> Add new 'enable_projects' argument for getCmakeExBuildFactory factory.

zorg/buildbot/builders/annotated/premerge/dispatch_job.py
`check-llvm` does not run tests for the `llvm-lit` utility, so run the `check-lit` target as well.
=> [CI] Add check-lit to postcommit testing

premerge/bigquery_schema/llvm_commits_table_schema.json, premerge/ops-container/process_llvm_commits.py
This changes adds additional fields for tracking whether a commit to llvm-project is a revert and what commit/pull request it is reverting.
Such commits are detecting by pattern matching against the commit message.
=> [CI] Track whether a commit is a revert
