buildbot/osuosl/master/config/status.py

* flang-runtime-cuda-gcc
* flang-runtime-cuda-clang

Add notification reporter for the Flang runtime builders.

---

zorg/buildbot/builders/annotated/hip-build.sh

This change is due to a GPU updated of the machine.

[HIP] Fixup gfx number for HIP buildbot

---

buildbot/osuosl/master/config/builders.py

Set option to have the build bot do clean builds.

Make builder llvm-new-debug-iterators do clean builds.

---

buildbot/osuosl/master/config/status.py

Jeremy Morse wants to be notified for failures of the llvm-new-debug-iterators buildbot as it is a configuration he is interested in.

Add notification for Jeremy Morse for llvm-new-debug-iterators builder.

---

zorg/buildbot/commands/LitTestCommand.py

https://github.com/llvm/llvm-zorg/issues/49

Fixed incorrect parsing of the failed LLVM/Clang Unit test names

---

buildbot/osuosl/master/config/builders.py
buildbot/osuosl/master/config/release_builders.py
buildbot/osuosl/master/config/workers.py

* added the "release" worker for the release builders.
* added ccache for llvm-clang-x86_64-expensive-checks-ubuntu* and lld-x86_64-ubuntu-fast* builders.

Update configuration for 'as-builder-4' worker and hosted builders.

---

zorg/buildbot/builders/sanitizers/buildbot_functions.sh

See https://github.com/llvm/llvm-project/pull/77687 for more details.

[sanitizers] Ensure we build LLVM's libunwind with the sanitizers

---

buildbot/osuosl/master/config/builders.py
buildbot/osuosl/master/config/workers.py
zorg/buildbot/builders/annotated/fuchsia-linux-staging.py

These builders will be used to for verify fuchsia build configuration changes.

Create dedicated staging builder fuchsia-x86_64-linux-staging 

---

buildbot/osuosl/master/config/builders.py
zorg/buildbot/builders/UnifiedTreeBuilder.py

Reverts llvm/llvm-zorg#133
This deserve Galina's review and I merged a bit too fast here.

Revert "Try adding an option to automatically install MLIR pip requirements to getCmakeWithNinjaBuildFactory"

---

buildbot/osuosl/master/config/builders.py
buildbot/osuosl/master/config/release_builders.py
buildbot/osuosl/master/config/workers.py

* changed target devkits for the remote tests.
* updated sysroot fs to Aarch64 Ubuntu 22.04.

Update configuration for llvm-clang-win-x-aarch64 and release builders.

---

zorg/jenkins/monorepo_build.py

* Rewrite artifact fetching/uploading logic in monorepo_build to use S3 Bucket rather than green-dragon-21
This code has been tested on https://green.lab.llvm.org

[green-dragon-migration] update monorepo_build to pull/store compilers with  s3

---

zorg/jenkins/inspect_log.py

* Simply update inspect_log.py to python3

[green-dragon-migration] Update inspect_log.py to python3

---

zorg/jenkins/clang_build_dependencies.dep

* Simply update os_version checked as part of the build process

[green-dragon-migration] update OS version

---

zorg/jenkins/common.groovy

* Update coming.groovy to use build URL for consoleText
* Pull from S3
* Don't send notification emails

[green-dragon-migration] Update common.groovy

---

zorg/jenkins/jobs/jobs/lnt-ctmark-aarch64-O0-g
zorg/jenkins/jobs/jobs/lnt-ctmark-aarch64-O3-flto
zorg/jenkins/jobs/jobs/lnt-ctmark-aarch64-Os
zorg/jenkins/jobs/jobs/lnt-ctmark-aarch64-Oz
zorg/jenkins/jobs/jobs/relay-lnt-ctmark

* Update LNT job label
* Update LNT relay job after structure changes

[green-dragon-migration] Update LNT jobs

---

zorg/jenkins/jobs/jobs/relay-test-suite-verify-machineinstrs
zorg/jenkins/jobs/jobs/test-suite-verify-machineinstrs-aarch64-O0-g
zorg/jenkins/jobs/jobs/test-suite-verify-machineinstrs-aarch64-O3
zorg/jenkins/jobs/jobs/test-suite-verify-machineinstrs-aarch64-globalisel-O0-g
zorg/jenkins/jobs/jobs/test-suite-verify-machineinstrs-x86_64-O0-g
zorg/jenkins/jobs/jobs/test-suite-verify-machineinstrs-x86_64-O3
zorg/jenkins/jobs/jobs/test-suite-verify-machineinstrs-x86_64h-O3

* Update test-suite job label
* Update test-suite relay job after structure changes

[green-dragon-migration] Update test suite jobs 

---

zorg/jenkins/jobs/jobs/clang-stage2-cmake-RgSan
zorg/jenkins/jobs/jobs/clang-stage2-cmake-RgTSan

* Update all existing stage 2 jobs
* Add declarative pipeline for stage2 sanitizers
All stage2 jobs have been updated to:
* Run on the correct labels
* upload artifacts to S3
* Set environment variables in `environment` closure when possible
* Setup python3 venv with all dependencies to build/test

[green-dragon-migration] Add stage 2 jobs

---

tasks/zorg-tests.sh
zorg/jenkins/jobs/jobs/zorg-tests

* Update the zorg test job, namely don't duplicate the unnecessary clone and install the necessary python requirements to run the tests

[green-dragon-migration] Update zorg test job

---

zorg/jenkins/jobs/jobs/clang-san-iossim
zorg/jenkins/jobs/jobs/clang-stage1-RA
zorg/jenkins/jobs/jobs/clang-stage1-RA-expensive
zorg/jenkins/jobs/jobs/clang-stage1-cmake-RA-incremental

* Update all existing stage 1 jobs
* Add declarative pipeline for stage1 expensive checks
All stage1 jobs have been updated to:
* Run on the correct labels
* upload artifacts to S3
* Set environment variables in `environment` closure when possible
* Setup python3 venv with all dependencies to build/test

[green-dragon-migration] Add stage 1 jobs

---

zorg/jenkins/jobs/jobs/clang-3.4-debuginfo-statistics
zorg/jenkins/jobs/util/submit-debuginfo-statistics-to-lnt.py

* Add declarative pipeline for debug info statistics jobs
Took the old job and converted it to declarative, also extracted the python code which lived in the jenkins UI into it's own maintainable file

[green-dragon-migration] Add lldb debug info statistics jobs

---

zorg/jenkins/jobs/jobs/lldb-cmake-as
zorg/jenkins/jobs/jobs/lldb-cmake-intel
zorg/jenkins/jobs/jobs/lldb-cmake-matrix
zorg/jenkins/jobs/jobs/lldb-cmake-sanitized
zorg/jenkins/jobs/jobs/lldb-cmake-standalone

* Update all existing lldb jobs
All lldb jobs have been updated to:
* Run on the correct labels
* upload artifacts to S3
* Set environment variables in `environment` closure when possible
* Setup python3 venv with all dependencies to build/test

[green-dragon-migration] Add lldb jobs

---

zorg/jenkins/jobs/jobs/relay-clang-stage2-sanitizers
zorg/jenkins/jobs/jobs/relay-clang-stage2-thinlto

* Update the relay jobs to conform to the new structure
( I don't know why, but git thinks I renamed one of the files. In fact I just deleted one and added a new one)

[green-dragon-migration] Fixup some relay jobs

---

zorg/buildbot/reporters/utils.py

Ignore `XFAIL:` lines in LLVMMessageFormatter

---

zorg/buildbot/builders/UnifiedTreeBuilder.py

A name of the source code profile to get from the remote repository. Currently is supported only "default" profile and None. Default is "default".
If None is passed, no the repository checkout steps will be added to the factory workflow. This is useful for the nested factories when the single repo is shared between them.
A supporting of multiply profiles will be added when it gets supported by Zorg core.

Add new 'repo_profiles' argument for UnifiedTreeBuilder.getCmakeExBuildFactory() factory.

---

buildbot/osuosl/master/config/builders.py
buildbot/osuosl/master/config/workers.py

x86_64/Linux Ubuntu host and Aarch64/Linux Ubuntu remote target.
Also added new 'as-builder-9' worker.

Add new LLDB remote-linux cross builder 'lldb-remote-linux-ubuntu'.

---

zorg/buildbot/builders/sanitizers/buildbot_android.sh
zorg/buildbot/builders/sanitizers/buildbot_bootstrap_asan.sh
zorg/buildbot/builders/sanitizers/buildbot_bootstrap_msan.sh
zorg/buildbot/builders/sanitizers/buildbot_bootstrap_ubsan.sh
zorg/buildbot/builders/sanitizers/buildbot_cmake.sh
zorg/buildbot/builders/sanitizers/buildbot_fast.sh
zorg/buildbot/builders/sanitizers/buildbot_functions.sh
zorg/buildbot/builders/sanitizers/buildbot_fuzzer.sh
zorg/buildbot/builders/sanitizers/buildbot_standard.sh

Remove -x from shell scripts

---

zorg/jenkins/jobs/jobs/clang-3.4-debuginfo-statistics

Add 12 hour timeout to debuginfo job

---

buildbot/fuchsia/Dockerfile

This is needed by LLVM libc newhdrgen.

Install PyYAML in Fuchsia Docker container

---

zorg/jenkins/jobs/jobs/clang-san-iossim
zorg/jenkins/jobs/jobs/clang-stage1-RA
zorg/jenkins/jobs/jobs/clang-stage1-RA-expensive
zorg/jenkins/jobs/jobs/clang-stage1-cmake-RA-incremental
zorg/jenkins/jobs/jobs/clang-stage2-Rthinlto
zorg/jenkins/jobs/jobs/clang-stage2-cmake-RgSan
zorg/jenkins/jobs/jobs/lldb-cmake-as
zorg/jenkins/jobs/jobs/lldb-cmake-intel
zorg/jenkins/jobs/jobs/lldb-cmake-matrix
zorg/jenkins/jobs/jobs/lldb-cmake-sanitized
zorg/jenkins/jobs/jobs/llvm-coverage

Disable Junit report archiving for the time being

Disable junit archiving

---

zorg/jenkins/jobs/jobs/lldb-cmake-intel

This will be used by the lldb-statistics job accordingly

Upload toolchain artifact with lldb intel job

---

zorg/jenkins/jobs/jobs/lldb-cmake-intel

call LLDB workaround correctly on binary in the install directory as well as the build directory

Set permissions on both install and build binary before uploading

---

zorg/jenkins/jobs/jobs/clang-3.4-debuginfo-statistics

Revert "[clang-3.4-debuginfo-statistics] Fix the LNT submissions run order"

---

zorg/buildbot/builders/sanitizers/buildbot_functions.sh

Reapply #250.
This reverts commit 3c5528ca96aed646236ce2421d0752746f7785ad.

Reapply "[sanitize] Don't build older then 1h requests"

---

buildbot/osuosl/master/config/builders.py
buildbot/osuosl/master/config/status.py
buildbot/osuosl/master/config/workers.py

Also add a new worker for the builder - as-builder-10.

Add a new LLDB remote-linux builder on Windows host (lldb-remote-linux-win).

---

zorg/buildbot/builders/sanitizers/buildbot_functions.sh

Buildbot is not ready yet https://github.com/llvm/llvm-zorg/issues/250#issuecomment-2485187944
This reverts commit 26a33cdbfaa6bbfc1feb1d76ce59fb727c072839.

Reapply "[sanitize] Skip build requests older than 3h" (#295)

---

buildbot/osuosl/master/config/builders.py

We have seen on this bot in particular issues with picking up a breaking change and some NFC change. This leads to the bot not commenting on the PR.

[AMDGPU][libc] Disallow collapsing of requests

---

buildbot/osuosl/master/config/builders.py

Add the actual dependencies of the bot.

[Offload] Fix depends-on-projects in CMake cache bot

---

buildbot/osuosl/master/config/builders.py
buildbot/osuosl/master/config/workers.py

Dockerized RHEL 9.4 builder that uses the Offload CMake Cache file AMDGPUBot.cmake as build config.

[Offload][AMDGPU] RHEL9.4 CMake Cache builder

---

buildbot/osuosl/master/config/builders.py

Additional projects got added in https://github.com/llvm/llvm-project/pull/124915

[AMDGPU] CMake-cache bots depend on MLIR and flang

---

buildbot/osuosl/master/config/builders.py

Include openmp runtime in flang AIX build

[AIX] [Flang] Add openmp runtime to the flang AIX build

---

buildbot/osuosl/master/config/builders.py

Adds a builder for libc on AMDGPU gfx90a to build and run tests.

[AMDGPU][Libc] Adds gfx90a libc builder

---

buildbot/osuosl/master/config/builders.py

This test is for some unknown reason quite flaky on this particular machine. Excluding it.

[AMDGPU][Offload] Exclude flaky test on one bot

---

zorg/buildbot/builders/annotated/amdgpu-offload-cmake.py

[AMDGPU] Fix tempfile import

---

zorg/jenkins/jobs/jobs/lldb-cmake-as
zorg/jenkins/jobs/jobs/lldb-cmake-intel
zorg/jenkins/jobs/jobs/lldb-cmake-matrix
zorg/jenkins/jobs/jobs/lldb-cmake-sanitized
zorg/jenkins/jobs/jobs/lldb-cmake-standalone
zorg/jenkins/jobs/jobs/lldb-statistics
zorg/jenkins/jobs/jobs/llvm-coverage

Print machine/xcode info in LLDB job output

---

zorg/jenkins/jobs/jobs/llvm-coverage

Prepend -Wl to -no_fixup_chains

---

premerge/main.tf

Updating the running version of GHA controller/listener/runner to the latest.

[presubmit] update arc version

---

zorg/jenkins/jobs/jobs/lldb-cmake-as
zorg/jenkins/jobs/jobs/lldb-cmake-intel
zorg/jenkins/jobs/jobs/lldb-cmake-matrix
zorg/jenkins/jobs/jobs/lldb-cmake-sanitized
zorg/jenkins/jobs/jobs/lldb-cmake-standalone
zorg/jenkins/jobs/jobs/lldb-statistics
zorg/jenkins/jobs/jobs/llvm-coverage

Print cmake version as part of node info stage

[lldb] Print cmake version in node info

---

buildbot/fuchsia/Dockerfile

This matches the buildbot master version used by lab.llvm.org.

[Fuchsia] Update buildbot package version

---

buildbot/fuchsia/Dockerfile

This is the latest released LLVM version.

[Fuchsia] Update LLVM version

---

buildbot/fuchsia/Dockerfile

26 is the latest Fuchsia SDK version.

[Fuchsia] Update Fuchsia SDK version

---

buildbot/osuosl/master/config/builders.py

Reduce memory usage when compiling the Flang related source code by specifying FLANG_PARALLEL_COMPILE_JOBS=12 for both builders.
Switch to one stage 'flang-rt' build on flang-runtime-cuda-clang builder.

Update configuration for flang-runtime-cuda-clang/gcc builders.

---

premerge/issues.md

This patch adds some more detailed documentation on dealing with the runner starvation issue, particularly touching on the maintenance actions that need to take place to deal with failed epehemralrunners while restarting failed runners with exponential backoff lands upstream in ARC.

[CI] Add detailed documentation on cleaning up failed epehemralrunners

---

buildbot/osuosl/master/config/builders.py
buildbot/osuosl/master/config/status.py
buildbot/osuosl/master/config/workers.py
zorg/buildbot/builders/annotated/libc-linux.py

We will be replacing the physical arm32 libc buildbot with an x86_64 buildbot using qemu.

Add arm qemu libc buildbot config

---

test/jenkins/test_build.py

Update the test after updating the build script configuration

Fix test/jenkins/test_build.py

---

zorg/buildbot/builders/BOLTBuilder.py

- Add a clean-nfc-check step to remove auxiliary files before nfc-mode-setup.
- Escalate errors in nfc-check-setup.py as warnings. Checks continue as expected.
- Allow tests to proceed if the old/new binaries are not generated. (rare case)
- Provide clearer message when GNU build IDs are embedded in the binary but they do match. Tests are skip accordingly.

[BOLT] Improve handling in BOLTBuilder and cleanup

---

buildbot/google/scripts/profcheck.sh
premerge/main.tf

This is to be run on VM startup to setup the machine and start the buildbot.

Add profcheck init script

---

buildbot/osuosl/master/config/status.py
buildbot/osuosl/master/config/workers.py

Send email to the group on new failures or when the buildbot is missing.

[ProfCheck] Add email notifiers

---

premerge/cluster-management.md

Clarify documentation on updating ARC version.

[llvm-zorg][CI] Minor fix to cluster management documentation.
